### ISSUE TITLE
Layer widget clip out of screen when sidebar is too small

### ISSUE THREAD

**Issue by locriacyber** [GraphiteEditor/Graphite#1005]
[layer-widget-clip.webm](https://user-images.githubusercontent.com/74560659/216038895-2aa5869b-5758-4aef-95be-a66c3b397f5a.webm)

Note the "folder" and "delete" icons

**Comment by Keavon** [comment]
Those are horizontally scrollable, but it would be nice to better handle the space allocation.

**Comment by locriacyber** [comment]
use flex-wrap
