### ISSUE TITLE
Backwards Compatibility???

### ISSUE THREAD

**Issue by LuminaSolis** [GraphiteEditor/Graphite#1007]
I'm getting a no 'backwards compatibility' error trying to open a file I literally worked on last night.... And nearly all my vector *.graphite files that have a JPG image embedded. 
Will graphite give this error if I moved the original JPG file to a different location or it something else? 
![error](https://user-images.githubusercontent.com/124408986/216734040-31c8f504-4a14-424a-a81d-2fc406474fb1.jpg)

**Comment by Keavon** [comment]
Hi, yes, unfortunately it's just not possible for us to support backwards compatibility at this early stage in development. We try to keep the deployment of breaking changes down to once or twice a month (on average).

Do you have the `.graphite` files or are you relying on the autosave feature? You can go back to an older version of the Graphite editor by viewing the changes on [this page](https://github.com/GraphiteEditor/Graphite/commits/master) and clicking the ✔ icon, then click "Details" to the right of "Cloudflare Pages — Deployed successfully". Then on the page it brings you to, click the "Preview URL" link. You may need to go back a few weeks to find a build that's still working, prior to this most recent change.

If you want to use the recent features in the latest Graphite version, you can try to copy and paste the layers from the old version to the new version. Some of the layers will probably be incompatible, but others might still be compatible. Likewise, you can probably copy some nodes from an old graph into a new graph if those specific nodes are compatible between versions. You can also export your artwork to PNG, JPG, or SVG and import it as a bitmap image back into Graphite.

I'm sorry for the hassle! I hope we can reach a point in the next few months where the document system can be stabilized. I hope you find this workaround usable in the meantime.

**Comment by LuminaSolis** [comment]
Thanks. I do have the .graphite files.  I knew it was only the files I have that a *.jpg layer in there to trace over into vector art.... The graphite versions before "[Replace the image layer type with an Image node]" work just fine.

Thanks for your help. I'm teaching a graphic design class and using Graphite. Perhaps not the best choice while it's still in development, but it remains the best option for free online software that doesn't require a log-in.

**Comment by Keavon** [comment]
Glad you were able to get a solution there! Yes, we're transitioning all the layer types to have their data be stored in the node graph, so that commit changed how images are stored (hence the file incompatibility).

That is very cool to hear you are teaching a class using Graphite. It would be valuable to hear your thoughts on the pain points from your experience, and the areas that your students find confusing or limiting. Please feel free to either [join the Discord](https://discord.graphite.rs) to talk about your findings, or otherwise file issues here requesting improvements.

**Comment by LuminaSolis** [comment]
Hi Keavon,
I hope this email still reaches you. I'm just hitting reply instead of
going through GitHub.

I've been trying to figure out how I used your backwards compatibility fix
per your last email, but I can't find the "cloudflare pages" link like
before. Is it in a different location or am I just not seeing it?

I've continued teaching my class using Graphite. It's gone fairly well
overall. It's very rare that my students continue working on a project past
the end of class, so usually the backwards compatibility issue doesn't
bother them, just me! The biggest problem as I see it with Graphite was it
kept crashing if you deleted a point while using the pen/ path tool. That
was fixed fairly recently. Today I had a crash after doing a bunch of color
fill/stroke edits and changing layer order; I hadn't saved recently enough
so that one was bad...

If I could push for a single change with the functionality of the pen/ path
tools in Graphite as it stands, I would ask that there be a clear way to
change the way the handles interact. If you create a closed shape using the
pen tool, then double click on each point using the path tool, each of
those anchor points will have handles on the side that are bound to each
other-- if you change one side of the anchor point, the other also changes.
One creative solution is to bring one handle into the anchor point,
essentially hiding or deactivating it, and then just use one handle per
achord point. The other creative solution is to double click along the
line, creating a new anchor point--- these anchor points have the amazing
property of having handles which are not bound to one another and can
independently change the line on either side of the anchor point. I've been
working with the linearity 'curve' app for ipad recently, and they have
really obvious solution for changing this anchor point property under the
'styles' tab; Inkscape has a similar solution.

Can you help me with the backwards compatibility issue again?

Thanks,
Elizabeth

**Comment by LuminaSolis** [comment]
Oh! I forgot to mention one fun thing! Something else I've discovered in
the course of teaching my class is that Graphite is one of the only vector
tools that will export an SVG file that doesn't make Scratch crash.
Scratch is a programming tool for children made by MIT that is extremely
popular in both the public education system and in the platform where I
teach, Outschool.com.
It's a nice selling point in any case, if you were looking for one.

Thanks again,
Elizabeth

**Comment by Keavon** [comment]
Regarding opening an old file:

Do you know roughly when it was created? Assuming it's from the past few months, can you open the file in a plain text editor and search for `commit_hash` then respond with the sequence of letters and numbers that comes right after that? I can find the build for that for you. It reminds me that I ought to make a more automated tool for that.

Regarding the crash:

I'm glad we were able to fix the one you were encountering often. The one you mentioned that happened recently is one I'm probably not aware of, so if you are able to reproduce it, please file an issue using the built-in error reporting procedure.

Regarding anchor point handles:

When they are locked to remain 180° from each other, they are called "smooth". You can tap the <kbd>Alt</kbd> key to switch them to "sharp" and this will unlock their 180° angle preservation. You can see this listed in the user input hints bar at the very bottom of the editor, which I recommend looking through closely to know what shortcuts are available to you at any particular time to learn the ins-and-outs of the program. We also recently added a Smooth/Sharp toggle to the Path tool's options bar which provides a way to view the current state and change it without requiring the shortcut key.
