### ISSUE TITLE
Node connections with incompatible types should be rejected instead of erroring

### ISSUE THREAD

**Issue by MultisampledNight** [GraphiteEditor/Graphite#1019]
Instead, this should reject the connection from occurring in the first place.

**Comment by Keavon** [comment]
The crash was fixed so I've edited this issue to now refer to no error being shown, so it can instead just reject the connection.

**Comment by 0HyperCube** [comment]
Is this ideal behaviour? If we have an add node that has implementations for `node(f64, f64) -> f64` and `node(vec2, vec2) -> vec2`, and by default used the f64 version, it would be impossible for the user to use the vec2 version because any attempts to connect a vec2 to either port would be immediately rejected.

**Comment by Keavon** [comment]
Excellent point! Yeah, they should probably just turn red then.

**Comment by MultisampledNight** [comment]
(fwiw Blender does the same, although sometimes I'd wish for a bit more feedback on _what_ exactly doesn't fit)

**Comment by 0HyperCube** [comment]
> Excellent point! Yeah, they should probably just turn red then.

@Keavon which input should turn red? Take the previous example of the add node for f64 and vec2. If the user connects an f64 and vec2 as input, which one should be highlighted red?

**Comment by Keavon** [comment]
Perhaps both? (So all become red if invalid.) If it's not crucial, I'd kind of like to just try it out before attempting to decide which is best in theory. But if that complicates implementation then I'm happy to take a closer look at evaluating and comparing the potential solutions to hopefully predict the best approach.

**Comment by 0HyperCube** [comment]
With #1535 now giving the correct indices for exposed inputs, it is mostly just a frontend change to add highlighting.
