### ISSUE TITLE
Middle click over node moves node, not view

### ISSUE THREAD

**Issue by MultisampledNight** [GraphiteEditor/Graphite#1023]
## Steps to reproduce

1. Create new node graph frame
2. Position cursor over `Image Frame` node
3. Press and hold middle click
4. Move mouse
5. See how node follows

## Expected result

To have the view move instead, like it's done when not over a node (and in other software like Blender).

**Comment by 0HyperCube** [comment]
Clicking and dragging on both nodes and the viewport currently works with any mouse button (not just middle click). Do we want to change this?

**Comment by Keavon** [comment]
The control scheme will change once we have box selection, but @MultisampledNight is that we'd expect MMB-drag to always pan the graph no matter what's under the cursor.

**Comment by Keavon** [comment]
Fixed in 8fe8896c4a6fea44eba1b3a37874d3a16068c3cc.
