### ISSUE TITLE
Crash with zero scale

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1043]
# Steps
- Open latest build https://dev.graphite.rs/
- Draw a rectangle
- Set the scale or dimensions to 0 in the properties panel by typing in the input field
- Confirm with enter
- Type a new number into the dimensions or scale field and press enter.
- `panicked at 'tried to transform point to non finite position', node-graph/gcore/src/vector/manipulator_point.rs:65:9`

**Comment by Keavon** [comment]
This also happens for a line drawn along the horizontal or vertical axis.
