### ISSUE TITLE
Add "Lock Angle" to Pen tool

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1048]
- [ ] The current `[Shift] Break Handle` behavior should become <kbd>Alt</kbd> instead of <kbd>Shift</kbd>
- [ ] The current `[Ctrl] Snap 15°` behavior should become <kbd>Shift</kbd> instead of <kbd>Ctrl</kbd>
- [ ] Implement the extend-in-this-direction feature called `[Ctrl] Lock Angle` that exists in the Line tool, but doesn't yet exist in the Pen tool

**Comment by ajjahn** [comment]
Dibs.
