### ISSUE TITLE
Drag-n-dropping a new image into a brand new document causes it to be imported with significantly higher dimensions than expected

### ISSUE THREAD

**Issue by AndreRoelofs** [GraphiteEditor/Graphite#1097]
## Describe the bug
When creating a new document and drag-n-dropping a 768x768 pixels image causes Graphite to import the image as a 1800000x1800000 pixels layer.

## To Reproduce
1. Create new document 1920x1080
2. Import a layer

## Expected behavior
The newly created layer has the same dimensions as the imported image.

## Priority
P0, the issue makes working with Graphite impossible.
[Reference - Google Issue tracker priority levels](https://developers.google.com/issue-tracker/concepts/issues#priority)

## Screenshots/Video
![image](https://user-images.githubusercontent.com/33526246/228238857-d0821f91-f816-4e41-941a-825b80babe84.png)
The proper image can be seen in right bottom corner.

## Desktop
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Resolution: 1920x1080
 - Version: Latest master branch 2023/03/28 14:42 CET

## Additional context
The problem has started occurring sometime after #1087

**Comment by Keavon** [comment]
Regression from #1065 @0HyperCube
