### ISSUE TITLE
Changing the dimensions of Spline Tool to overly large number freezes the website

### ISSUE THREAD

**Issue by AndreRoelofs** [GraphiteEditor/Graphite#1101]
## Describe the bug
When changing the dimensions of the Spline Tool (and probably other similar ones) to an unreasonable number the website freezes. Such a behavior can occur during normal workflow if the user clicks on the dimensions input and removes all the numbers left of the dot accidentally. I had to disable javascript, log back into the website, clear cookies and re-enable javascript in order for the website to continue working.

## To Reproduce
1. Go to https://editor.graphite.rs/
2. Create new document 1920x1080
3. Choose the Spline Tool
4. Draw a random line
5. Change the height in the properties tab to be an overly large value, say 40927980640203.

## Expected behavior
The app clamps the input to a reasonable upper limit

## Priority
P2, the issue can only happen in a normal workflow if the user clicks on the dimensions input and removes all of the numbers left of the dot. Clearing the cookies solves this issue.
[Reference - Google Issue tracker priority levels](https://developers.google.com/issue-tracker/concepts/issues#priority)

## Screenshots/Video
Not possible to add as the website freezes upon the input of a large number.

## Desktop
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Resolution: 1920x1080
 - Version: Latest master branch 2023/03/31 18:15 CET

## Additional context
The user shouldn't be able to crash their computer while working with the tool.

**Comment by Keavon** [comment]
Is this still an issue? It doesn't freeze on my end using the current https://editor.graphite.rs

**Comment by AndreRoelofs** [comment]
The issue has indeed been resolved.
