### ISSUE TITLE
Embedded bitmap files are massive, use base64 instead

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1117]
Every pixel is stored like this (excerpt of two pixels shown here):
```
...{"red":0.13333334,"green":0.23529412,"blue":0.14117648,"alpha":1.0},{"red":0.24705882,"green":0.28235295,"blue":0.2,"alpha":1.0},...
```
We should ideally save as base64.

This slows down the autosave system too, causing long editor freezes at unexpected times.

**Comment by 0HyperCube** [comment]
Closed by #1120
