### ISSUE TITLE
Make the Spline tool non-destructive

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1125]
Instead of adding points to a temporary list stored in the Spline tool, which gets destructively committed when the user is done and turned into a Bezier curve, move that spline -> Bezier logic into a node and make the Spline tool draw a polyline which gets fed into the spline interpolator node.

**Comment by 0HyperCube** [comment]
Part of #134

**Comment by Keavon** [comment]
Closing as part of #134.
