### ISSUE TITLE
Add layer locking

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1127]
Add a 🔒 to layers to prevent them from being selected in the viewport. It should still allow selection in the Layer Tree panel, and updating of values in the Properties panel, but shouldn't allow viewport-related interaction (using the tool and certain actions accessible from hotkeys and/or the menu bar).

**Comment by Cioraz** [comment]
In this, suppose a layer is locked then you mean we should be able to use any tool on that layer right? However the properties panel still allows modifications on that layer

**Comment by Keavon** [comment]
Correct.

**Comment by Keavon** [comment]
@haikalvidya please comment in this issue.

**Comment by haikalvidya** [comment]
This issue is closed on this PR https://github.com/GraphiteEditor/Graphite/pull/1702
