### ISSUE TITLE
npm start showing errors

### ISSUE THREAD

**Issue by ukmothukuri** [GraphiteEditor/Graphite#1143]
Hi, i'm using the below stack.

- Ubuntu 20.04
- node -- v18.16.0
- rustc -- 1.68.2
- cargo -- 1.68.2

on npm start, shows the below errors:

Compiled with problems:

ERROR in ./src/wasm-communication/editor.ts (/home/ukm/Graphite/frontend/src/wasm-communication/editor.ts) 1:36-59
[tsl] ERROR in /home/ukm/Graphite/frontend/src/wasm-communication/editor.ts(1,37)
      TS7016: Could not find a declaration file for module '@graphite/../wasm/pkg'. '/home/ukm/Graphite/frontend/wasm/pkg/index.js' implicitly has an 'any' type.
ERROR in ./src/wasm-communication/editor.ts (/home/ukm/Graphite/frontend/src/wasm-communication/editor.ts) 61:27-50
[tsl] ERROR in /home/ukm/Graphite/frontend/src/wasm-communication/editor.ts(61,28)
      TS7016: Could not find a declaration file for module '@graphite/../wasm/pkg'. '/home/ukm/Graphite/frontend/wasm/pkg/index.js' implicitly has an 'any' type.

Let me know if anything i've missed.

**Comment by Keavon** [comment]
Hi! That error is likely indicating that the Rust code failed to compile. Sometimes you just need to trigger a rebuild by re-saving a Rust file so the watcher triggers a rebuild. Killing and restarting the build may also help. Or, if you've changed any code, try looking earlier in the console output for Rust errors, or run `cargo check` to validate for compiler errors. Happy to help you troubleshoot further if that doesn't do the trick.

**Comment by ukmothukuri** [comment]
It is working fine now after reinstalling the rustc.

**Comment by Keavon** [comment]
Excellent!
