### ISSUE TITLE
Listing the previously created designs in the Welcome Screen

### ISSUE THREAD

**Issue by ukmothukuri** [GraphiteEditor/Graphite#1147]
How to store the designed documents in the same server? So that i can view the previously created designs in the welcome screen and select a document(.graphite files) for any enhancement.

**Comment by Keavon** [comment]
This isn't currently possible because the browser has no access to your file system. You have to upload each file when you intend to open it.

Closing this for now since there's no action we can currently take, but feel free to discuss further.
