### ISSUE TITLE
Spline does not have mirror handles enabled

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1174]
A shape produced by the spline tool does not have mirror handles enabled, meaning that when you switch to the path tool and drag a handle, the opposite one does not automatically move. The expected behaviour is that it should remain mirrored, similar to when a similar action is taken with an ellipse. To resolve this, the mirror handle setting should be enabled when creating a spline in `spline_tool.rs`, you can use `ellipse_tool.rs` as reference for setting the mirror.

**Comment by Chase-Percy** [comment]
Hi, new here! I'd like to look at this (and a few of the other good first issues :p).

**Comment by Keavon** [comment]
Welcome @Chase-Percy, this would be a great place to get started. Please feel free to join [our Discord](https://discord.graphite.rs) and reach out to 0Hypercube there if you need any pointers. Thanks for volunteering :)
