### ISSUE TITLE
Make the show/hide layer button work

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#118]
Start with `core\editor\src\dispatcher\mod.rs:40` and plumb the state updates through the document layer system's visibility state. It needs to end up in the state encoded in a `LayerPanelEntry` in `core\document\src\response.rs:9` which gets sent through the WASM back to the frontend.

**Comment by akshay1992kalbhor** [comment]
Hey, can I work on this?

**Comment by Keavon** [comment]
Yes, this should be available. Feel free to ping me on Discord and I can answer some questions if you need any help, or through GitHub in this discussion if you don't use Discord. Thanks for volunteering!

**Comment by TrueDoctor** [comment]
ou basically only have to call the already exposed wasm functions from vue, add an operation for it and handle to operation in the document.
This also has be added to the dispatcher

**Comment by Keavon** [comment]
To clarify, this is actually already piped from the Vue through the WASM to the code in `core\editor\src\dispatcher\mod.rs:40`.

**Comment by akshay1992kalbhor** [comment]
Thanks guys. I am still reading the code to understand what's going on. Your comments have also been helpful!

**Comment by akshay1992kalbhor** [comment]
Should probably close this one. @Keavon

**Comment by Keavon** [comment]
For future reference, you can write "closes #118" in your commit message and it'll close the associated issue for you.
