### ISSUE TITLE
When text is modified in the Properties panel, it shifts around

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1180]
Editing the text in the properties panel causes the position of the text in the document to shift (we need to update the position when the text changes, as the position is relative to the centre of the text). This only happens if the text has a scale other than 1x1 in X and Y.

**Comment by milan-sedivy** [comment]
Is this still relevant? I'm failing to reproduce this (or don't understand what the bug exactly is).

**Comment by 0HyperCube** [comment]
@milan-sedivy Here is a screen capture of the bug. The left side of the text should not move but does.
[text_shift.webm](https://github.com/GraphiteEditor/Graphite/assets/78500760/f4910b37-4cf0-4019-a7a3-a1f546ec03b8)

**Comment by milan-sedivy** [comment]
@0HyperCube I've managed to analyze it and found where the issue stems from. Will probably take a bit more time to properly fix this, i.e. I have a hot-fix that resolves this issue, but I'm currently not sure if it breaks other functionality, gonna test and evaluate it now.

**Comment by Keavon** [comment]
@0HyperCube just checking, do you expect this would cause any conflicts with your changes in #1589?

**Comment by 0HyperCube** [comment]
This is to do with the transform pivot so so will conflict

**Comment by Keavon** [comment]
Gotcha, I think that's acceptable if they conflict since it shouldn't be too big of a change.

**Comment by 0HyperCube** [comment]
https://github.com/GraphiteEditor/Graphite/pull/1558 fixes this issue.

**Comment by Keavon** [comment]
Oh, in that case I'll mark it so it closes this.
