### ISSUE TITLE
Stroke and fill color choices should be on all vector tools

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1192]
#1191 added the Fill and Stroke color choices to the options bar of the Pen tool.

![image](https://user-images.githubusercontent.com/4388688/235793388-c61cf79b-350c-4e9f-bc51-bfc292dbe7a7.png)

The next step is to bring that to all tools:

![image](https://user-images.githubusercontent.com/4388688/235793241-d5c086e4-32e7-4046-9adb-05b52da91070.png)

As indicated in the image, the Line tool will only have the stroke but not the fill choice. And the Text tool will only have the fill but not the stroke choice.

The code should aim to be generalized as much as feasible to avoid too much duplication.

**Comment by Chase-Percy** [comment]
Sounds good, so it's all the tools in the image? Like the square, circle, etc?
