### ISSUE TITLE
Replace Fill node's "Use Gradient"/"Use Solid Color" button with a radio button

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1219]
![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/24903b31-4ac2-444a-9432-b17db82aed0b)

If you draw a shape, its Fill node has that, with a "Use Gradient" (and if you click it, "Use Solid Color") button at the bottom.

![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/c61b8066-4046-47f3-a994-c95ced524e08)

I'd like to replace those two buttons with a radio button toggle, just like you see in that second screenshot with "Linear" and "Radial".

Instead of being at the bottom, it should be at the top. It should say "Solid" and "Gradient" as its two choices. I suggest copying the Gradient Type (Linear/Radial) row and modifying it to do what the "Use Gradient"/"Use Solid Color" buttons currently do. A very good way to approach any new task if to locate the code by searching the whole project for a unique-looking string, in this case "Use Solid Color" would be a good thing to search for. For the enum that backs the radio button, you can use this one called `FillType`: <https://github.com/GraphiteEditor/Graphite/blob/duplicating_layers_layer_tree/node-graph/gcore/src/vector/style.rs#L210-L217> (as a tip to explain my thought process, I searched the project for `::Gradient` and forced it to match only the full word and be case-sensitive, and I found that enum in use in a few places)

**Comment by rotteegher39** [comment]
I'll try to work on this.

**Comment by elsa-linu** [comment]
@Keavon Hey, I would like to try this issue.

**Comment by Keavon** [comment]
@elsa-linu sorry, it's already completed. Please hop on Discord and ask me for another issue suggestion.
