### ISSUE TITLE
Questionable float <-> int conversion in a variety of places

### ISSUE THREAD

**Issue by orlp** [GraphiteEditor/Graphite#1227]
As [an example](https://github.com/GraphiteEditor/Graphite/blob/38b4050d9e31affb2a528d005006a4708f237a5d/node-graph/gcore/src/raster/color.rs#L571):

```rust
pub fn to_rgba8_srgb(&self) -> [u8; 4] {
    let gamma = self.to_gamma_srgb();
    [(gamma.red * 255.) as u8, (gamma.green * 255.) as u8, (gamma.blue * 255.) as u8, (gamma.alpha * 255.) as u8]
}
```

I find this questionable, because literally only the value `1.0` can map to the `u8` value `255`. `1.0 - 1e-9` which is infinitesimally smaller does not map to `255`. This problem exists in a few places.

As `float as u8` conversion in Rust [automatically clamps to `[0, 255]`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ccc7dce52aa6302f4473018ffe198373), I would suggest `(f * 256.0) as u8` instead.

**Comment by orlp** [comment]
The [D3D11 spec](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#FLOATtoSRGB) specifies a different conversion method: `(f * 255.0 + 0.5) as u8`. I don't know if we want to use that instead.

**Comment by Keavon** [comment]
Let's use the + 0.5 since that sounds much more intuitively correct.

**Comment by Keavon** [comment]
This was solved recently. (I think.)
