### ISSUE TITLE
Add point position inputs to Path tool options bar

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1229]
In place of these red boxes, I'd like to have two number inputs for X and Y values that display the position of the currently selected point.
![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/121b4477-5b2d-415f-8c33-1feb596d3e7f)

Other tools have widgets there, such as the Pen tool:
![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/336a5737-2952-40a0-834e-63b318c4f866)

That bar where the widgets go is called the options bar.

If no points are selected, or if multiple points are selected, the number inputs should be disabled.

**Comment by olit123** [comment]
I'll give this a go :)

**Comment by hexofyore** [comment]
.

**Comment by Keavon** [comment]
Hi @hexofyore @olit123 just checking in how things are going and if you need any help :)

**Comment by hexofyore** [comment]
@Keavon I was busy. I am going to do it this weekend.

**Comment by Keavon** [comment]
No worries, thanks for the update :)

**Comment by olit123** [comment]
@Keavon Hey yeh it's been a busy couple of weeks for me, slowly trying to get to grips with this project and prerequisite knowledge in my spare time but I am very noob. Will definitely be asking questions when I'm ready.

**Comment by omagdy7** [comment]
I can try this if it's still available

**Comment by Keavon** [comment]
Go for it @omagdy7!

**Comment by mobile-bungalow** [comment]
I would like to try this if there is if it's available. As a side note,  I got the [feature working on my fork](https://github.com/GraphiteEditor/Graphite/compare/master...mobile-bungalow:path_point_options) to learn the code base, if that helps anyone who is trying this in the future.

**Comment by Keavon** [comment]
Awesome, good to hear @mobile-bungalow! I've assigned you to this issue. Please open a PR when you're ready!
