### ISSUE TITLE
Color palette from image

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1230]
Create a node which analyzes the colors of an input image and produces a palette in the form of a vec of colors as output.

A good starting point for some background reading: https://spin.atomicobject.com/2016/12/07/pixels-and-palettes-extracting-color-palettes-from-images/

**Comment by henrybarreto** [comment]
I was searching for an opportunity to start contributing to the project, despite my non-artistic background.

It seems to my good entry point to it. @Keavon, I would to try solving this issue.

Is there more information that I should to know before starting?
