### ISSUE TITLE
Tracking Issue: Enable WebGPU graph execution

### ISSUE THREAD

**Issue by TrueDoctor** [GraphiteEditor/Graphite#1232]
Moved to #144

**Comment by Keavon** [comment]
The latest browser support status

- **Safari:** now behind a flag in Technical Preview as of December 21, 2023 (https://webkit.org/blog/14879/webgpu-now-available-for-testing-in-safari-technology-preview/)
- **Firefox:** behind a flag in Nightly (https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#webgpu_api), progress towards stabilization tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1616739
- **Chromium:** shipped for all users on Windows 10+, Mac, and ChromeOS. Linux and Android are behind a flag (and require Canary?)

See also:
- [caniuse](https://caniuse.com/webgpu)
- [MDN compat table](https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API#browser_compatibility)

**Comment by Keavon** [comment]
Moved to #https://github.com/GraphiteEditor/Graphite/issues/144.
