### ISSUE TITLE
Path tool should have a box selection on drag

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1234]
Just like the Select tool's path box selection that occurs when clicking and dragging an open region, this should also happen with the Path tool to select the available anchor points (but probably not handle points?). In the future, this feature could also be extended to do a lasso selection region (instead of a simple box) when dragging with a hotkey held, like in Blender.

**Comment by dhruv-ahuja** [comment]
I'm going to take this up.
