### ISSUE TITLE
Allow nodes to have no primary output

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1235]
The primary input is optional for nodes, but the primary output is currently required. The Split Channels node needs to have no primary output. Add support for this, and remove that node's primary output connector.

**Comment by gautamprikshit1** [comment]
Additional help please

**Comment by Keavon** [comment]
Hi @gautamprikshit1, I assume you're interested in working on this task and requesting assistance with where to get started on it? If so, it's easier to chat about it on Discord, could you [join that](https://discord.graphite.rs) and introduce yourself there so we can start a conversation about this issue? Thanks!
