### ISSUE TITLE
Change how Vue sends input to the backend

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#124]
We are currently binding keys in Vue. This was set up as a temporary measure. We'll want to properly send input events to the WASM code without involving Vue. Some considerations:

* [x] All keyboard input should be sent to the WASM
* [x] Only mouse inputs targeting the viewport should be sent, not those involving clicks on GUI elements
* [x] Mouse that has dragged outside the viewport should continue to be sent until (and including) release
* [x] Properly handle (to the best of its abilities) events when the application has been removed from focus in the OS
* [x] Use input to outside-the-viewport items to help reconstruct the status of inputs that may have been interrupted while mouse button was down in a viewport interaction and then focus lost
* [ ] Support multiple panels at once
* [ ] Generic approach so it can be used in other panel types, like the Layer Graph
* [ ] Consideration should be put into pen inputs, and other types of input devices

**Comment by TrueDoctor** [comment]
Alt + Shift keys are combined into a `meta` key press.
![image](https://user-images.githubusercontent.com/21245806/119231311-833b9600-bb20-11eb-8b51-cdda6cc8bd55.png)

One way of fixing this would be to send the current modifier state (+ pressed mouse key)
as additional information in the events to the input preprocessor. This gives the input preprocessor more information to work with and reduces the impact of missed key events.

**Comment by TrueDoctor** [comment]
+ Add scroll wheel handling to the js and the input preprocessor.
https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent

**Comment by Keavon** [comment]
I'm moving this back to Available, but it will require some experience in webdev to properly implement this in a way that doesn't conflict with Vue. If you take this issue, please work closely with me to make sure all considerations are dealt with.

**Comment by Keavon** [comment]
We should standardize on the names of each key defined in https://www.w3.org/TR/uievents-code/#key-alphanumeric-writing-system
