### ISSUE TITLE
Add a sharp/smooth anchor toggle to the Path tool

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1249]
Similar to #1229, there should be a radio input to toggle between Sharp and Smooth added to the Path tool's options bar.

- Sharp: an anchor's two handles can be any angle
- Smooth: an anchor's two handles are locked at a 180° angle offset

Users can currently toggle between the two while dragging a handle by tapping the <kbd>Alt</kbd> key. This toggle widget in the Properties panel should help visualize the current state of things if an anchor is selected, and/or one or both of its two handles.

If one handle is selected, clicking the toggle to change to Smooth should cause the opposite handle to rotate (but not change length) to be 180° from the selected one. If an anchor and/or both handles are selected (meaning there isn't one specific handle), then clicking switching to Smooth should rotate the angles of both handles to their average rotation (also without affecting their lengths). When switching from Smooth the Sharp, don't change their angles or lengths.

**Comment by parkma99** [comment]
I'll give this a go :) I am a newer for this project, could you give me some tips to start? @Keavon

**Comment by Keavon** [comment]
Redirecting to @0HyperCube since I'm on vacation, thanks

**Comment by 0HyperCube** [comment]
@parkma99
- We can add some logic to detect if a point is sharp or smooth in `PathToolMessage::DocumentIsDirty` branch in `path_tool.rs`.
- We need to check if there is a single selected point. This can be done with `self.selected_points().count() == 1`. If there is not just a single selected point, we should not show the widget.
- We need to access the vector data of the currently selected point. This can be done with something like `let (layer_id, point) = shape_editor.selected_shape_state.iter().flat_map(|(layer_id, state)| state.selected_points.iter().map(|point|(layer_id, point))).next()?` (ignore my ugly iterator usage).
- We need to access the current vector data for the layer, which contains the positions of the points with `document.layer(layer_id).ok()?.as_vector_data()?;`
- Get the current mirror state, this can be done with `vector_data.mirror_angle.contains(point.group)`.
![image](https://github.com/GraphiteEditor/Graphite/assets/78500760/c4be774b-8ff3-45d2-9101-252799e56daf)
- We can now store booleans for `current_sharp` and `single_point_selected` in `PathToolData`.
- To display this, we need to add to the existing `impl PropertyHolder for PathTool {}`, probably using the `RadioInput` widget. See other code for examples of how to add widgets.
- To ensure that the widget is rendered when the state changes, you can call `self.register_properties(responses, LayoutTarget::ToolOptions);` on the `PathTool`.
- When the user changes the sharp by clicking, pipe a message (as can be seen in other tools).
- Currently the logic for changing sharpness is in `flip_sharp` - feel free to adjust / split up this function as necessary (it is currently quite long).

If you have any questions, the discord guild is probably the fastest way to get them answered.

**Comment by parkma99** [comment]
Thanks @0HyperCube , I will have a look late.😊

**Comment by mobile-bungalow** [comment]
I have a PR ready for this if it's open.
