### ISSUE TITLE
Better node insertion dropdown

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1280]
Currently when a new node is inserted into the node graph through the right click menu, the list is difficult to work with.
![image](https://github.com/GraphiteEditor/Graphite/assets/78500760/e056aede-1235-4974-ad07-3b01dd97881f)
A scroll bar and a collapsed dropdown for each category would help with this.

**Comment by Keavon** [comment]
@FadedBronze could I have you please reply in this thread so I can assign you to this issue for tracking/organization purposes? Thanks again for making this.

**Comment by FadedBronze** [comment]
> @FadedBronze could I have you please reply in this thread so I can assign you to this issue for tracking/organization purposes? Thanks again for making this.

Your welcome.
