### ISSUE TITLE
Issue Calculating Offsets/Normals for Linear Curves in `bezier-rs`

### ISSUE THREAD

**Issue by crahda** [GraphiteEditor/Graphite#1287]
Hi!

I'm trying to use the `bezier-rs` library to draw some basic Bezier curves; as part of this work, I wanted to define a linear curve (straight line) which is parallel to another linear curve, such that a line segment drawn between their midpoints would be perpendicular to both lines.

Roughly, the code I'm using looks like:

```rust
// Define the first line.
let line = Bezier::from_linear_dvec2(start, end);

// Define the second line, offset by 0.25 from the first line.
let parallel: Subpath<GradientId> = line.offset(0.25);
```

However, the behavior of the offset lines doesn't match my expectations--if I sample points along both lines (via `compute_lookup_table(Some(100), None)`), I get a plot showing that the midpoints of the two lines would not form a perpendicular line segment (for reference, the "primary" line is green/grey with a red midpoint marker, and the "offset" line is blue):

![newplot](https://github.com/GraphiteEditor/Graphite/assets/8396541/b016d760-6351-4295-b99e-fb0ce5de93ef)

For additional context, the data I'm plotting is relatively small (it ranges from `-0.4` to `0.4`), and in these graphs the primary line segment starts at `(0, 0)` and ends at `(-0.136231, 0.066667)`.

This could totally be user error on my end--is there a better/correct way for me to achieve the result I'm looking for?

**Comment by Keavon** [comment]
It's possible this is a numerical stability issue. If you increase the scale of your plot, does that make it end up closer to expectations?

**Comment by crahda** [comment]
🤔 That could make sense!

Using this updated example code with a scale factor of `100.0f64`:

```rust
let line = Bezier::from_linear_dvec2(start * 100.0f64, end * 100.0f64);

// Define the second line, offset by 0.25 from the first line.
let parallel: Subpath<GradientId> = line.offset(0.25 * 100.0f64);
```

I unfortunately get a similar plot:

![newplot(1)](https://github.com/GraphiteEditor/Graphite/assets/8396541/7d3acb88-ed2c-4e4a-b352-2580924fbc74)

In both cases, I'm plotting the points obtained via `compute_lookup_table(Some(100), None)` for both `line` and `parallel`.

**Comment by Keavon** [comment]
Sorry, I'm really not sure what might be happening here. In the [interactive docs](https://graphite.rs/libraries/bezier-rs/#bezier/offset), offset for a linear segment seems to be working fine. Perhaps as a workaround, you can use [normal](https://graphite.rs/libraries/bezier-rs/#bezier/normal) to find the normal vector and offset your curve by that?

**Comment by crahda** [comment]
No problem! For the sake of completeness, I went ahead and tried using the `normal` function to create a perpendicular ("normal") line relative to the primary `line`:

```rust
let line = Bezier::from_linear_dvec2(start * 100.0f64, end * 100.0f64);

// Calculate a point that is `distance` away
// from the midpoint of the line, traveling along
// a line normal to the line.
let midpoint = line.evaluate(TValue::Parametric(0.5));
let normal = line.normal(TValue::Parametric(0.5));
let distance = distance * 100.0f64;
let normal_point = midpoint + distance * normal;
let normal_to_point = Bezier::from_linear_dvec2(midpoint, normal_point);
```

When plotted in the same way as the previous examples, I got the following result (the blue line is _supposed_ to be normal/perpendicular to the green-grey line):

![newplot(2)](https://github.com/GraphiteEditor/Graphite/assets/8396541/6726d6cb-6eea-47e0-aeb9-a57ac90a2aa9)

**Comment by 0HyperCube** [comment]
I have plotted your example in desmos @crahda - the red line starts at (0,0) and ends at (-0.136231, 0.066667). The offset by 0.25 blue line starts at (-0.10988923461161798, -0.22455368203721973) and ends at (-0.24612023461161797, -0.15788668203721973), matching the bezier-rs library and my own maths:
![image](https://github.com/GraphiteEditor/Graphite/assets/78500760/af962d7e-7bc7-40c2-a2ff-887af00705d2)
Perhaps you were confused because in your own graph, the scale on the X axis is different from the scale on the Y axis?

**Comment by crahda** [comment]
Oh no--I'm very silly. 🤦

Yes, the issue was with the axis scales not matching, causing visual distortion. Using my first set of example code with the axes _fixed_, I get a plot that shows the expected geometry:

![newplot(4)](https://github.com/GraphiteEditor/Graphite/assets/8396541/1d3fdac1-fb2d-4054-bdba-7be3c3947779)

I'm happy to say the issue was on my end, and can be closed; thank you both so much for helping investigate this issue!
