### ISSUE TITLE
Make arrow key nudge-resizing operate in document space

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1317]
The nudge system correctly moves by 1px (or 10px when <kbd>Shift</kbd> is held down) relative to the document (so the nudge happens regardless of viewport zoom). However, nudge-resizing is currently viewport-relative which isn't desired, and this means the zoom level ends up factoring itself into your new scale value (which can be especially undesirable if the view is at a noninteger ratio, causing the selected layers to render with antialiasing because they will have lost grid alignment).

- Nudging is using the arrow keys to move the selected layers around within the canvas.
- Nudge resizing is using the arrow keys, while also holding <kbd>Alt</kbd>, to resize the bottom and right edges of the selected layers (or top and left if <kbd>Ctrl</kbd> is also pressed)

---

The following might no longer be relevant after the unified node graph refactor when the nudge system was rewritten to use the document graph (in #1501). But last time we tried switching from viewport space nudging to document space nudging, the following problem occurred. It's left here for context if necessary.

> Currently, if you select a layer and change its size with <kbd>alt</kbd> + arrow key then the layer gets a seemingly arbitrary translation also. This is related to `DocumentMessage::NudgeSelectedLayers`. A reasonable approach would be to not change the translation of the layer, so that the pivot does not move.
> 
> Note that we don't want to use the actual pivot point for the layer (![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/5a495387-bccd-413e-910a-1ab83aa7bf69), controlled by dragging it or this widget: ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/4973a00b-aa1d-470d-8746-e9c40026d67d)). We want to use the top left of the bounding box since that's more useful for positioning the layer which is what this nudge-resize feature is used for.
> 
> This is a regression introduced in #1114, which correctly switched from viewport-space to document-space for nudging but introduced this functionality regression for nudge resizing. A correct fix will need to change how the transforms calculate the final size so it doesn't cause an unintended translation.

**Comment by Keavon** [comment]
https://github.com/GraphiteEditor/Graphite/assets/4388688/bd48cc5a-0b36-4e04-a417-c494741c6e1f
