### ISSUE TITLE
Select all points in path tool

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1318]
The user should be able to press <kbd>Ctrl</kbd><kbd>A</kbd> to select all the points. This should happen only in the path tool, and should not change the currently selected layers.

In order to achieve this, a new function should be added to the `ShapeState` struct that allows selection of all points in all layers. This function should iterate through `&mut self.selected_shape_state`, accessing the current vector data for each layer. For each group in `vector_data.manipulator_groups()` and for each selected type in `[SelectedType::Anchor, SelectedType::InHandle, SelectedType::OutHandle]`, we need to run `state.select_point(ManipulatorPointId::new(group.id, selected_type));`.

**Comment by henryfranceschi** [comment]
I would like to try working on this.

**Comment by gautamprikshit1** [comment]
Are you still working on this one @henryfranceschi

**Comment by henryfranceschi** [comment]
No, it was never assigned to me, I didn't do much work on it. @gautamprikshit1

**Comment by 0HyperCube** [comment]
Would you like to continue with this @henryfranceschi or can I assign it to @gautamprikshit1?

**Comment by henryfranceschi** [comment]
You can assign it to @gautamprikshit1.
