### ISSUE TITLE
Snapping options dropdown

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1319]
Populate the dropdown menu for the snapping system shown below. Some initial features would be a checkbox for snap to node and a checkbox for snap to bounding box, however this will be added to as more snapping features are added.
![The snapping dropdown](https://github.com/GraphiteEditor/Graphite/assets/78500760/37de350a-4945-4d61-ad96-3a68b8cf1886)
The inkscape snapping options box for inspiration (although we don't need icons for the initial version):
![Inkskape snapping options](https://github.com/GraphiteEditor/Graphite/assets/78500760/5315f93f-b2e9-474c-bb82-e0019a9f4c63)
In order to add this, we need to change the `PopoverButton` widget to have `options_widgets: WidgetLayout`. We also need to modify `PopoverButton` in `frontend/src/wasm-communication/messages.ts` and change the svelte component `frontend/src/components/widgets/buttons/PopoverButton.svelte` to display the options instead of the placeholder text.

**Comment by dhruv-ahuja** [comment]
I want to give this a go :)
