### ISSUE TITLE
Path points persist on screen after deleted

### ISSUE THREAD

**Issue by dchiasson** [GraphiteEditor/Graphite#1330]
If a path point is selected via the path tool and then deleted, the path is updated properly, but a visual artifact of where the path point used to be remains on the screen until the browser is refreshed:

![image](https://github.com/GraphiteEditor/Graphite/assets/1863441/c7bce061-86ff-4fea-a275-9ced07242972)

**Comment by 0HyperCube** [comment]
Thank you for reporting this issue @dchiasson.

This issue has already fixed by a recent commit. To see the latest build of the main branch, visit https://dev.graphite.rs/. We plan to update https://editor.graphite.rs/ soon.
