### ISSUE TITLE
Can draw path point on top of vertical scroll bar

### ISSUE THREAD

**Issue by mickvangelderen** [GraphiteEditor/Graphite#1349]
Can draw path point on top of vertical scroll bar. I wanted to move the viewport but ended up adding a new path segment too. Used the mobile web version.

**Comment by Keavon** [comment]
Are you talking about the Pen tool? I can't reproduce that based on my interpretation of your description. Can you please provide a highly detailed step-by-step reproduction, or a video?

**Comment by Keavon** [comment]
I'm going to close this until more information is provided. Please follow up and then I can reopen this.

**Comment by mickvangelderen** [comment]
Just noticed this. Maybe it's fixed then.
