### ISSUE TITLE
Holding space whilst dragging gets stuck transforming canvas

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1351]
If you hold space and then continue to do so whilst dragging with the left mouse button, notice how if you release the space bar before you release your mouse, you get stuck in the canvas moving mode. This should not happen - you should always stop moving the canvas when you release your mouse (whatever is happening to the space key). 

The code for ending a transformation of the camera can be found in `editor/src/messages/portfolio/document/navigation/navigation_message_handler.rs:211`.
This is send by the input map here `editor/src/messages/input_mapper/default_mapping.rs:319`.

**Comment by Ezbaze** [comment]
I'll take this one 🫡
