### ISSUE TITLE
Dropdown button for rotating camera

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1352]
Currently the viewport can be rotated by holding <kbd>Ctrl</kbd> whilst dragging with the middle mouse button. This is however difficult to find. A similar option should be added to the menu bar at the top of the app, in the view menu to rotate the canvas.

The code for the menu bar can be found in `editor/src/messages/portfolio/menu_bar/menu_bar_message_handler.rs:250`.
The code for the canvas rotation can be found in `editor/src/messages/portfolio/document/navigation/navigation_message_handler.rs:197`.

Inspiration can be taken from similar views in inkscape and illustrator 
![inkscape camera orientation dropdown](https://github.com/GraphiteEditor/Graphite/assets/78500760/7e338d01-4b5f-4a6f-b0c2-aca7ebd3a641)![illustrator camera rotate dropdown](https://github.com/GraphiteEditor/Graphite/assets/78500760/ed7e772b-a36f-416e-be15-22d51ed07ad8)

**Comment by Keavon** [comment]
I prefer the Inkscape option since it's less verbose. Clicking that menu item should enter rotation mode. The hint bar should be sure to mention the hotkey for angle snapping.

**Comment by omagdy7** [comment]
I would like to work on this

**Comment by Keavon** [comment]
Apologies @omagdy7, it wasn't assigned yet but @Ezbaze is already halfway through implementing this. Please reach out to me on Discord if you'd like help picking another suitable issue for you to begin work on.

**Comment by Ezbaze** [comment]
Working on it
