### ISSUE TITLE
Hints for changing brush tool size

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1360]
When using the brush tool, the size of the brush can be changed with <kbd>[</kbd> and <kbd>]</kbd>, however this is not shown in the hints bar (at the bottom of the application)
![Hint bar](https://github.com/GraphiteEditor/Graphite/assets/78500760/c4dbe41f-d396-4d00-ba2c-70d0d53b050a)

Code for brush tool hints is at editor/src/messages/tool/tool_messages/brush_tool.rs:434

**Comment by omagdy7** [comment]
Working on this
