### ISSUE TITLE
problem with avast antivirus

### ISSUE THREAD

**Issue by evaggelosevaggelou** [GraphiteEditor/Graphite#1374]
Hello. I try to run the application but avast antivirus gives me the message that the application https://editor.graphite.rs/ is infected with url: blacklist

**Comment by Keavon** [comment]
It's flagging a website, not a downloadable program?

**Comment by evaggelosevaggelou** [comment]
I enter the website normally, but when I click lounche it forbids me from entering 
![screenshot 12](https://github.com/GraphiteEditor/Graphite/assets/5406984/2c4058d8-deb7-47c9-abba-391bf46bc31c)

**Comment by TrueDoctor** [comment]
I'll try to contact the avast support

**Comment by TrueDoctor** [comment]
I got a response and they said it was a false positive and would be fixed with the next update.  @evaggelosevaggelou could you try to retest this?

**Comment by evaggelosevaggelou** [comment]
It works perfectly...

**Comment by TrueDoctor** [comment]
Nice! thanks for confirming!
