### ISSUE TITLE
Change Brightness/Contrast node implementation to reuse Curves node

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1387]
Brightness/Contrast and Curves repeat a lot of code. This cleanup involves changing the Brightness/Contrast node so it acts as a document node wrapping the Brightness/Contrast node whilst providing it the necessary input parameters. Care should be taken to ensure that all unit tests pass with `cargo test`.

**Comment by jafriyie1** [comment]
Hello, if no one has taken this task I would like to work on this!

**Comment by Keavon** [comment]
That would be great, go for it! Be aware that it needs to pass the tests which have hard-coded arrays for the reference values. You'll need to convert between those when running the tests to ensure the results remain the same even though the approach changes.

Thanks!

**Comment by jafriyie1** [comment]
Sounds good! If I run into any issues or if I have questions, I'll be sure to ask on the discord since this is my first time working on this project.

**Comment by Keavon** [comment]
Perfect! 👌

**Comment by jafriyie1** [comment]
Hey @0HyperCube and @Keavon ! So I am less familiar with the conventions used here, but is it ok if I mark the [PR](https://github.com/GraphiteEditor/Graphite/pull/1434) on this as ready to be reviewed? I have finished working on this a while back ago, but I left the PR as a draft since there isn't any mention on if one of the maintainers will change the status of the PR, or not, once it is ready to be reviewed. Thanks :)

**Comment by Keavon** [comment]
Thanks for asking! Yes, you're in charge of marking the PR as a draft vs. ready-for-review depending on whether you're waiting on us or vice versa. Making a comment in the PR to ping one of us, or on Discord, is also helpful so we know to request ourselves as reviewers (if you lack the permission to request us directly).

We also typically discuss the particulars of a PR in the comments for the PR, rather than the issue that's referencing it (i.e. this issue).

But I just want to check with you to confirm you've made sure the tests still pass in that PR, since if that isn't the case then it'll require some additional work until we begin the review.

Thanks again!
