### ISSUE TITLE
[Crash Report] Creating cycle with nodes causes crash

### ISSUE THREAD

**Issue by Comeza** [GraphiteEditor/Graphite#1392]
## Describe the Crash
Feeding the a layer (or any other) node into itself causes the editor to crash.
![image](https://github.com/GraphiteEditor/Graphite/assets/37485277/c8e88455-48f1-455d-8576-cd69d8bb6500)

As noted in the error log, a cycle is detected.
But this should not cause the editor to crash and data to be lost.

## Steps to reproduce
- Create a new document
- Feed the output of the layer node into the input (See image)
- *Crash*

## Stacktrace
```
ns/<@https://editor.graphite.rs/index.0536bdd5.js:25:3480
handleJsMessage@https://editor.graphite.rs/index.0536bdd5.js:17:46021
ai/e<@https://editor.graphite.rs/index.0536bdd5.js:17:82856
Qr/t.wbg.__wbg_call_4c73e4aecced6a7d/<@https://editor.graphite.rs/index.0536bdd5.js:17:78203
Kr@https://editor.graphite.rs/index.0536bdd5.js:17:51369
Qr/t.wbg.__wbg_call_4c73e4aecced6a7d@https://editor.graphite.rs/index.0536bdd5.js:17:78165
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[805]:0x2cf630
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[3504]:0x47c4cc
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[3391]:0x475cd3
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[5321]:0x4f576b
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[822]:0x2d6759
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[822]:0x2d696c
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[822]:0x2d696c
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[240]:0xbb33a
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[830]:0x2dc139
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[522]:0x237c92
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[1889]:0x3db83e
@https://editor.graphite.rs/graphite_wasm_bg.360fb6cb.wasm:wasm-function[5814]:0x4fd462
Hr@https://editor.graphite.rs/index.0536bdd5.js:17:50725
i@https://editor.graphite.rs/index.0536bdd5.js:17:50186
```

Full error log: https://pastebin.com/HgY0xZk4

**Comment by 0HyperCube** [comment]
Thank you for the crash report @Comeza. Stopping the user from creating connections that would create a cycle or lead to incorrect types is a high priority item for node graph UX improvements.

**Comment by TrueDoctor** [comment]
This should return a proper error and not just panic because users could upload faulty documents, hence it might not be enough to restrict this in the UI. @Comeza would you be interested in working on this? Should be relatively simple to fix, basically just propagating the error upwards (similar to how we currently treat type errors).

**Comment by toadkarter** [comment]
I can have a look at this one, feel free to assign it to me!
