### ISSUE TITLE
Select Tool: Viewport layer click selection

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#140]
Click a layer in the viewport to select it. We'll probably want to add a `data-` attribute to each SVG element to identify its path and just use `addEventHandler` to handle the click event. ~~Depends on #137.~~

This pertains to the Select Tool.
![Select Tool](https://files.keavon.com/-/UselessDevotedOzarkbigearedbat/capture.png)

Complexity: 1
Involves: Frontend (JS)

**Comment by Keavon** [comment]
Blocked presently on #100.

**Comment by Keavon** [comment]
@pkupper I believe this is unblocked now that #100 is closed from merging #175. Is there anything else I might be forgetting about that's a blocker? (If so, I can re-add the Blocked label.) Do you think it would be feasible to get this finished up and merged by either this weekend (in time for the Rust Gamedev newsletter) or the coming week (in time for the end of the sprint and the Rust Gamedev Meetup live demo)? I would be really excited to show off your great work with this (and, if possible, #207) in a week to the folks watching the Rust Gamedev Meetup if it works within your schedule over the coming week.

**Comment by pkupper** [comment]
#175 is mostly done. I rebased on the canvas transform changes last weekend. There are only two minor open issues where deselecting when clicking empty space does not work and the tolerance when selecting lines depends on the length of the line. I will definitely be able to fix those up this weekend, although most likely tomorrow.
