### ISSUE TITLE
Handle multiple documents

### ISSUE THREAD

**Issue by TrueDoctor** [GraphiteEditor/Graphite#142]
Add the ability to have multiple documents open at the same time.
The selection of documents is already handled in the editor, but the ability to add/delete documents has to be added.
Most of the work involves using the tabs to manage documents in the frontend.
![image](https://user-images.githubusercontent.com/21245806/119252852-b88ec500-bbae-11eb-96d3-a4fcbca581c5.png)

Complexity: 2
Involves: Frontend (JS), Editor (Rust)

**Comment by Keavon** [comment]
@geom3trik do you have any updates on this?
