### ISSUE TITLE
Dragging vector points with Path tool should use absolute positions

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1420]
Right now we move a delta. This means when we drop frames (like when the developer console is open, or #1284), it don't move by the expected amounts. It also means we accumulate floating point error and other nastiness.

We should store the mouse drag start position, and the positions of all the points. Then take the new absolute mouse position each frame, recalculate the offsets, and move the points to those locations.

A goal should be that, when the viewport is zoomed to 100% scale, if the user drags a point that has a clean integer position (no numbers after the decimal), dragging that point should make it end up at another position that's also a clean integer position.

**Comment by wzwywx** [comment]
Hello, I'm new and would like to contribute, but I'm still unclear on how to approach this one even though it seems simple.

Is it not enough to just convert  `input.mouse.position` into an absolute value when assigning the `snapped_position`?

https://github.com/GraphiteEditor/Graphite/blob/b9027883a8535abcaf15c51ce3491b8d36734cbb/editor/src/messages/tool/tool_messages/path_tool.rs#L397C6-L397C109

**Comment by Keavon** [comment]
@TrueDoctor could you help answer this? I'm unfamiliar with how it's actually implemented. Thanks.

**Comment by TrueDoctor** [comment]
I actually don't think this is a good first issue because this requires pretty complex design work and is part of the document graph migration, I'll most likely start working on this soon (I expect 500-1000 loc of changes)

**Comment by 0HyperCube** [comment]
This is not an issue any more because we now rely on the input to the shape node rather than the previous node graph evaluation.
