### ISSUE TITLE
Select Tool: Grab/drag selected layers around viewport

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#143]
If the user has no layers selected, this will select the layer under the cursor (see #140) and then drag (transform) it. If multiple are selected, and the drag occurs on one of the selected, it will drag (transform) all of them. If one or more are selected but the drag occurs on another layer, it deselects the current selection and selects the new layer and drags it (like in the first sentence).

After this is implemented, we can then add support for snapping: #200.

Complexity: 3
Involves: Editor (Rust), Document (Rust)

**Comment by Keavon** [comment]
@pkupper do you know if this task is blocked, or soft-blocked in some capacity, by your work on #178?

**Comment by pkupper** [comment]
This is does require #178. I'll see how much work this is and perhaps include it in my PR. We haven't really had the need to modify existing Layer yet so it will require some new Document Operations

**Comment by Keavon** [comment]
Blocked on #243.

**Comment by Keavon** [comment]
@AyeTbk you might like this one.

**Comment by henryksloan** [comment]
I'd like to take this one, now that Fill is merged.

**Comment by Keavon** [comment]
Some additional features for this one: <kbd>Shift</kbd> hotkey constraints to a 15° angle, and adding the <kbd>Ctrl</kbd> hotkey locks to that particular constraint angle no matter where you move your mouse after. But let's merge the basic feature before the modifier keys.
