### ISSUE TITLE
Changing the sides for a polygon and then dragging broken

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1443]
Steps to reproduce:
- Open the editor
- Select the polygon tool (pentagon icon on the left)
- Click in the "Sides" input at the top and type 6 (don't press enter or confirm)
- Start dragging a new polygon in the document.
- Observe how it only has 5 sides. Future polygons will have 6.

**Comment by Keavon** [comment]
@tnmkr please comment here so I can assign you to this completed issue.

**Comment by tnmkr** [comment]
> @tnmkr please comment here so I can assign you to this completed issue.

Hi, please assign this to me :)
