### ISSUE TITLE
Graphite on Smaller Screens and Keyboard Shortcuts

### ISSUE THREAD

**Issue by 7xa5h** [GraphiteEditor/Graphite#1449]
So, when you check out Graphite on smaller screens, it's very zoomed in. Here's what I mean ![](https://us-east-1.tixte.net/uploads/xash.tixte.co/wIqodB.png)Basically, you can barely see anything, and you've got to zoom out and do some serious scrolling just to get to the tools you need.

There's a simple solution: We could do what Pixlr did ![](https://us-east-1.tixte.net/uploads/xash.tixte.co/bFvLjA.png) and stack the tools, so you don't have to struggle with zooming and scrolling. Plus, it'd be awesome if we can give users the option to hide that bottom bar, creating more workspace.

Now, about those keyboard shortcuts – the current setup is kinda tricky. When you want to close a file, you're supposed to use Ctrl+W, but that ends up closing the whole webpage, so another thing we could do is change it to something like Ctrl+Q or any other key combo that won't accidentally close the whole thing?

By making these changes, we'll make Graphite more user-friendly, especially for people on smaller screens, and keep things simple and intuitive for everyone.

**Comment by 0HyperCube** [comment]
Thanks for the suggestions. Making the tool shelf have multiple columns is already tracked in #176.

**Comment by 0HyperCube** [comment]
You can use <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>W</kbd> to close the tab, or alternatively if you enter full screen in a chromium based browser, you can use the shortcut as normal.
