### ISSUE TITLE
SVG Export a bit iffy

### ISSUE THREAD

**Issue by everythingability** [GraphiteEditor/Graphite#1451]
Hi,

Mac M2/Chrome/Ventura 13.5.1 (22G90)

Just messing about....I added a graphic, painted a but and some vector elements, and an ink and transparency to the graphic and exported as SVG , but the graphic and paint elements in Inkscape look like this. Seems to only export the vector elements.

<img width="668" alt="exported image viewed with Inkscape" src="https://github.com/GraphiteEditor/Graphite/assets/96276/99f06b4f-c2ee-4871-b789-56dfd1a81017">

The file that was exported was:
![Untitled Document](https://github.com/GraphiteEditor/Graphite/assets/96276/7f76a31e-f76b-4910-849e-72f739840d6b)

The graphite file is/was:
[Untitled Document.graphite.zip](https://github.com/GraphiteEditor/Graphite/files/13279305/Untitled.Document.graphite.zip)

Great work btw. Thanks

Tom

**Comment by Keavon** [comment]
Thanks for the report. This is somewhat expected as we're in the middle of a big refactor that changes a lot of SVG rendering-related things. I think this should mostly improve itself as we continue forward. But we'll keep an eye out for what you encountered in particular! I'll keep this issue open until it's resolved.

**Comment by 0HyperCube** [comment]
Closed by #1495
![Exported blender logo](https://github.com/GraphiteEditor/Graphite/assets/78500760/6a9f6556-d1fb-4a80-810e-898557ae2d05)
