### ISSUE TITLE
Brush lines have gaps

### ISSUE THREAD

**Issue by NinthDesertDude** [GraphiteEditor/Graphite#1461]
The brush leaves gaps in contiguously drawn lines (circled in red below)
![image](https://github.com/GraphiteEditor/Graphite/assets/30244654/752bb767-1974-42bd-8c25-3009827b9565)

It should interpolate between the previous and current point with linear lines or a continuous spline, dividing the segment length based on some percent of the brush size so it can be evenly spaced along the lines. Whatever it's currently doing is leaving these gaps, sometimes large.

**Comment by 0HyperCube** [comment]
Thanks for reporting this bug @NinthDesertDude . We already have linear interpolation between points based on the spacing parameter. I'm currently unable to reproduce this issue. Would it be possible for you could give more precise instructions on how to reproduce this?

**Comment by NinthDesertDude** [comment]
Brush size should be 1. I see gaps that end up being an issue in rendering (they go away after zooming and panning), but I also see gaps that exist when the bitmap is exported. I had tested both. Set brush size to 1, hold down the mouse and move it in circles. I was able to repro this with other mice and other computers that had other mice. It was repro'd in Chrome and Firefox
