### ISSUE TITLE
Add folders in the Layer Tree panel of the frontend

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#149]
Documents (and layer paths) involve a nested layer structure. But currently everything is added flatly to the root because the frontend does not support folders. We need to add folders to the Layer Tree panel which can represent the nested layer structure and display the information provided by the Editor backend. After that, we'll be able to rearrange layers into the folders (#141) and select other layers that will be the hierarchical target for new layers to be drawn as siblings of (or a folder for new layers to be children of).

Still left to do:
- [ ] Fix frontend layer rendering JS (@Keavon)
- [ ] Make it so we can copy and paste hierarchy, not just flat layers. This also includes the ability to select multiple layers at various levels in parts of the hierarchy and it copies each of them, to eventually be pasted as new siblings (descendants of selected folders are de-duplicated). (@TrueDoctor)
- [ ] When a layer (shape or folder) is selected and being grouped, we copy and delete its deepest common ancestor folder, put a new folder exactly in its place (including its original index among its siblings), then paste back into that new folder. In the special case of root (because we can't delete the root), we select everything in root, delete everything, create a new folder, then paste everything in that single folder. (@TrueDoctor)

Complexity: 3
Involves: Frontend (JS)

**Comment by azeemba** [comment]
I was considering working on this.

I looked at the `LayerPanelEntry` interface at https://github.com/GraphiteEditor/Graphite/blob/master/client/web/src/utilities/response-handler.ts#L204-L210
It does have the `layer_type` flag which identifies something as a `Folder`. It's not clear to me though how to determine what other layers belong to this folder. Is the goal of this issue to update this interface? Or is that structure encapsulated in the "path" that needs to be decoded?

**Comment by Keavon** [comment]
This is a frontend task that involves two major things. One: building the HTML/CSS for the actual hierarchical layer structure. Two: retrieving `ExpandFolder` and `CollapseFolder` messages and maintaining a JavaScript object in the frontend which is mutated by those two messages. Any time a folder is collapsed, we empty that part of the hierarchy and any children. If anything is updated in a folder, a whole new status is sent for that folder to replace it (but not replace its child folder contents).

**Comment by Keavon** [comment]
I also want to mention, for some context, that this is one of the more high-priority features and it is best to have it done by next weekend since other tasks somewhat pertain to it. You are more than welcome to ask all the questions you need and get help being un-stuck, please don't hesitate to reach out. If you prefer a more beginner friendly task with a slightly less high-priority timeline, I can also recommend a few for you as alternatives to this one. If you think you're up for the task (all power to you!) then by all means please proceed but I'd greatly appreciate a draft PR early on and some status updates every few days, just because it's important to not let this particular feature fall into limbo. Thanks for your understand!

**Comment by azeemba** [comment]
Definitely don't want to be a blocker. Happy for anyone else to tackle it
