### ISSUE TITLE
Document > Clear Artboards should not delete its children

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1505]
Instead of deleting its children, it should ungroup those children from the artboard and then delete just the artboard, leaving the artwork behind. The code for ungrouping with Ctrl+Shift+G can probably be referenced to achieve a similar outcome here.

We also want the same for deleting an artboard from the Artboard tool, where the artwork remains behind.

(However, when deleting from the Layers panel, we do want the current behavior of deleting its children since that's also how deleting folders in the Layers panel works, so no change there.)

A continuation of #1502

**Comment by 0HyperCube** [comment]
Do you want an artboard deleted normally to avoid deleting nested layers? Do you want a deleted group to delete nested layers?

**Comment by Keavon** [comment]
Normally, if the user selects an artboard in the Layers panel, it's expected that its contents also get deleted. But specifically the Document > Clear Artboards menu (which should maybe be renamed to something like "Use Infinite Canvas" although I don't love that name either) would have the purpose of dumping all the artwork into the infinite canvas if the user didn't want artboards (like, perhaps, they started with an artboard by default and at some point decided they want a more freeform unbounded experience for collaging or whiteboarding).

**Comment by skoriop** [comment]
Hi, I was thinking of tackling this issue. To confirm, this is how the node graph should look like before and after clicking `Document > Clear Artboards` right?

Before:
![image](https://github.com/GraphiteEditor/Graphite/assets/116057817/00dbbebc-441e-483e-8386-795199d77832)

After:
![image](https://github.com/GraphiteEditor/Graphite/assets/116057817/4904514e-2175-4f67-b1b8-ce71ff39dd80)

**Comment by Keavon** [comment]
Without that layer on the right, either. @skoriop
