### ISSUE TITLE
New Tool: Fill Tool

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#152]
The Fill Tool changes the fill color property for the layer which gets clicked on by setting it to the primary working color. Although it will eventually be a raster tool for flood filling a thresholded range of colors in an area of the raster image, we can duplicate its icon and turn it blue and move it to the bottom section of tools to use it as a way to change the color of shapes that click on it.

**Comment by henryksloan** [comment]
I'm currently working on this.
