### ISSUE TITLE
Crash when dragging stroke weight

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1528]
Creating a rectangle on the main branch (local or release) and dragging the stroke weight field leads to "unreachable executed" silent crash (no crash dialogue)

https://github.com/GraphiteEditor/Graphite/assets/78500760/c05f169f-b52e-4386-a624-8e717b8f14e9

**Comment by Keavon** [comment]
We should also try to figure out why this doesn't trigger the crash dialog and see if we can remedy that more universally for this silent kind of crash.

**Comment by 0HyperCube** [comment]
I cannot reproduce this anymore - this may be the same issue as #1561.
