### ISSUE TITLE
New Tool: Text Tool

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#153]
Clicking somewhere creates a Text Layer at that location and begins letting the user type. This translates to a [`<text>` SVG tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text) on the canvas. While editing the text, the user can type stuff. <kbd>Return</kbd> is a new line but <kbd>Enter</kbd> (on the numpad) applies the text, as does <kbd>Ctrl</kbd><kbd>Return</kbd>. The Text Tool also lets you click anywhere over an existing text layer and begin editing that text in the location clicked.

**Comment by 0HyperCube** [comment]
@Keavon A few challenges with this:
- We need to find the length of glyphs (characters in the font) so we can place the cursor, find the bounds of the textbox and handle moving the cursor to the right place when clicking on existing text.
- Also we probably need to be able to convert text to a path (involving the backend parsing `.ttf` files or similar which could then also be put into a font attribute in svg - https://www.w3.org/TR/SVGTiny12/fonts.html - this would solve the glyph length problem above)
- We should probably follow OS preferences such as sticky keys (shortcuts for people with reduced motion), cursor blink speed / width as well as properly handling support for Chinese / Japanese / Korean.

**Comment by Keavon** [comment]
I was planning to just make it use the SVG [<text>](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text) tag and let the browser worry about most of those details. It won't be fancy, just enough to work.

**Comment by 0HyperCube** [comment]
> The Text Tool also lets you click anywhere over an existing text layer and begin editing that text in the location clicked.

@Keavon The `<text>` tag handles rendering the text, however it does not tell me which character I've clicked on, or display a blinking cursor if I'm editing the text.

**Comment by Keavon** [comment]
@0HyperCube just checking in on your progress. Would you be able to push a WIP PR?
