### ISSUE TITLE
Graph UI links disappear

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1548]
Occasionally the graph UI links disappear `Graph.svelte`.

**Comment by iacore** [comment]
how do I reproduce this?

**Comment by Keavon** [comment]
At the moment it's not clear. Fiddle around with it until you're able to cause it again, then please report back with reproduction steps. (Anyone who wants to help with that can be useful by commenting here with steps.)

**Comment by iacore** [comment]
Is this the view opened with the "Node Graph" button? I don't see any links.

**Comment by Keavon** [comment]
Yes.
