### ISSUE TITLE
New Tool: Navigate Tool

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#155]
Pan, rotate, and zoom the canvas.

Left click drag up/down = zoom in/out
Right click drag around center of canvas = rotate around center of canvas
Middle click drag = pan

![Navigate Tool icon](https://files.keavon.com/-/SpiffyMeaslyGentoopenguin/capture.png)

**Comment by 0HyperCube** [comment]
Additional controls: (from inkscape and gimp)
- Middle mouse button + mouse move - pans document (gimp and inkscape)
- <kbd>Space</kbd> + mouse move - pans document (gimp and inkscape)
- <kdb>ctrl</kbd> + right mouse drag - pans document (inkscape only)
- <kbd>ctrl</kbd> + scroll - zooms document around the location of the mouse (inkscape and gimp)
- <kbd>+</kbd> or <kbd>-</kbd> - incremental zooming (gimp and inkscape) - probably easier for user if shift isn't required.
- Zoom input field + input increment buttons - Change zoom
- Another set of (are they necessary?) zoom increment buttons in top right of viewport - incremental zooming
- Also to consider: Input field for rotation (gimp and inkscape)
- <kbd>ctrl</kbd> + mmb drag - mouse drag up - zoom in, down zoom out (gimp)
- <kbd>ctrl</kbd> + mmb drag - rotate viewport around centre (inkscape)
- <kbd>shift</kbd> + mmb drag - rotate viewport around centre (gimp)
- <kbd>shift</kbd> +  <kbd>ctrl</kbd> + mmb drag - rotate viewport around center with 15° intervals  (gimp)

**Comment by Keavon** [comment]
Thanks for collating those, that's very helpful. I'll try and come up with a whole keymap for Graphite soon, and I will edit the original issue description with those. Ping me if you're blocked by needing a specific answer.

**Comment by Keavon** [comment]
To be completed in follow-up to #229.

**Comment by Keavon** [comment]
@0HyperCube I just wanted to mention that I've mentally earmarked this feature for you since tools and navigation are your prior work. If you get the chance to spend some time in the next month before the alpha release on this feature, the would be awesome to help with tool catalog feature completeness. (Ignore that this says Sprint 11, it's always great to work on things earlier.) If you don't have time soon, or this doesn't pique your interest, no worries— I'm just mentioning it to put this on your radar.
