### ISSUE TITLE
Get CI to check if demo artwork renders successfully

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1551]
We want CI to guard against breaking the renderability of the demo artwork.

@TrueDoctor how easy is this?

**Comment by TrueDoctor** [comment]
We should be able to just add a unit test for this right?

**Comment by Keavon** [comment]
Yes, that was what I meant by CI (unit tests checked by CI).

**Comment by TrueDoctor** [comment]
In that case pretty easy

**Comment by Keavon** [comment]
Feel free to add a test for this when you get a little spare time then! It would be valuable in the short-term to help us avoid mistakes. It just needs to ensure the actual graph renders real output.

**Comment by 0HyperCube** [comment]
https://github.com/GraphiteEditor/Graphite/blob/444929adbfa090f1b20fbf4c6f3a832bb4a826cd/editor/src/dispatcher.rs#L463-L471
