### ISSUE TITLE
Node panics shouldn't bring down the editor

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1552]
Sandbox various components, like the node graph, in panic handlers. Reload those components instead of having to reload the whole page. Avoid making the document get lost since that's highly destructive to the user and almost always shouldn't be corrupted by whatever bug resulted in the crash, so the document data should most likely be in tact.

Some options:
- Move the graph evaluator into a web worker?
- Something with panic handlers?
- Reboot the node graph executor somehow?

**Comment by TrueDoctor** [comment]
@Keavon should we close this or remove it from the in progress tasks?

**Comment by Keavon** [comment]
Closed by #1846
