### ISSUE TITLE
Path tool sliding point insertion

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1578]
For the Path tool, instead of double clicking to insert a point like it is now, we want it so instead you click *once* and it shows a sliding dot (similar to Shift+V or GG in Blender to slide a point) and it lets you move the point where the split happens, then clicking again applies it (or right clicking to cancel, or maybe moving the mouse far away cancels it).

**Comment by Nikita-str** [comment]
Hi, seems like I can do it, assign it to me, please

**Comment by Keavon** [comment]
Awesome, welcome! I'll assign it to you once you've opened a PR.

**Comment by 0HyperCube** [comment]
@Nikita-str you can add a function to `graph_modification_utils.rs`:
```rs
pub fn get_stroke_width(layer: LayerNodeIdentifier, network: &NodeNetwork) -> Option<f32> {
	if let TaggedValue::F32(width) = NodeGraphLayer::new(layer, network)?.find_input("Stroke", 2)? {
		Some(*width)
	} else {
		None
	}
}
```
