### ISSUE TITLE
Spelling typo : accessability --> accessibility

### ISSUE THREAD

**Issue by DesignThinkerer** [GraphiteEditor/Graphite#1600]
https://github.com/GraphiteEditor/Graphite/blob/1bf62d92c23f87e2ccff75905dae055f0c7d76f9/website/content/features.md?plain=1#L216

**Comment by Keavon** [comment]
Thanks, I'll include a fix with some website changes I'm just about ready to commit.

**Comment by Keavon** [comment]
Fixed now. Thanks again for the report.
