### ISSUE TITLE
Avoid layers being reordered when dealing with groups

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1633]
- Grouping (with <kbd>Ctrl</kbd><kbd>G</kbd>):
    - [x] #1627:
        **External consistency:** Grouping the selected layers causes the group to be inserted at the top of the layer stack. It should go just above where the layer selected layers were located.
        The current incorrect behavior:
        | ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/fa51a964-ee79-43f4-8e0e-c75f17f1fcf7) | -> <kbd>Ctrl</kbd><kbd>G</kbd> -> | ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/6228cc38-78f6-4c57-acb8-772dcece6b13) |
        | - | - | - |
    - [x] #1645
        **Internal consistency:** Grouping layers should also preserve the order that they were sorted once those layers end up in the new group
        The current incorrect behavior:
        | ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/378dae38-f131-45e7-83c6-4aa3bdebac2e) |  -> <kbd>Ctrl</kbd><kbd>G</kbd> -> | ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/2edbfdd0-5223-4149-876b-cafa34a9a650) |
        | - | - | - |
- Ungrouping (with <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>G</kbd>):
    - [ ] #1672
        **External consistency:** Ungrouping should also preserve order by placing the content in the hierarchy where the group used to be.
        The current incorrect behavior:
        | ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/30beb10b-b252-4111-a8ac-a3054430c54b) | -> <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>G</kbd> -> | ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/b6b38eaf-4c03-45dd-9204-d79bcd45a9a4) |
        | - | - | - |
    - [x] #1645
        **Internal consistency:** While ungrouping, the content in the group itself should also be have its order preserved amongst its grouped siblings.
        The current incorrect behavior:
        | ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/ae7f926e-88d6-43e1-b209-9602c5204de4) | -> <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>G</kbd> -> | ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/6b588a43-4a8f-4552-ae51-5fdf08e3dd59) |
        | - | - | - |
- Creating a new folder  (with <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>N</kbd> while in fullscreen mode of the web app, or the folder button in the top bar of the Layers panel):
    - [x] #1678
        Should be placed directly above the topmost selected layer in the hierarchy (at the level of the least nested layer)
        The current incorrect behavior:
        | ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/0d951ade-9454-462e-9490-35577db885b7) | -> this button is clicked -><br />![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/eab72dbc-9498-4655-9aad-a084e131451a) | ![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/783f24f4-40fb-456e-8e00-63b9e3b8116e) |
        | - | :-: | - |

**Comment by Keavon** [comment]
@moOsama76 Please reply "Ok" so I can assign you this issue.

**Comment by moOsama76** [comment]
Okay!
