### ISSUE TITLE
Transform node crashes app when scale == 0

### ISSUE THREAD

**Issue by Kakapio** [GraphiteEditor/Graphite#1635]
This is primarily an issue when dragging the scale parameters to adjust them in the UI. When the value for scale hits 0 on either x or y, Graphite crashes. I'm gonna look into this myself and try to patch it up (since I'm new 😄) but I'm making an issue to document it. 

My solution is to just ignore an input of 0 in the backend. Let me know if that's too sloppy.

**Comment by Kakapio** [comment]
issue only seems to occur when a TransformNode -> RepeatNode...

**Comment by devharsh2k4** [comment]
any updates?

**Comment by devharsh2k4** [comment]
any updates?

**Comment by Kakapio** [comment]
> any updates?
> 
> 

There are several upcoming refactors so this issue is being put aside for now.

**Comment by Keavon** [comment]
Yeah, it's potentially blocked by @TrueDoctor's work on https://github.com/GraphiteEditor/Graphite/pull/1558

**Comment by 0HyperCube** [comment]
As far as I can tell (please include the actual panic message in future) this is probably from failing to inverse a transform matrix containing 0 in debug mode? We likely need to special case the zero transform such that we don't end up inverting.

@Keavon / @Kakapio I struggle to see how this is relevant to a change in the pivot code.

**Comment by Keavon** [comment]
Thanks for chiming in @0HyperCube, perhaps this doesn't need to be blocked then (it just needs to have a zeroness check in the correct place, like where you suggested with the inverse transform matrix).

**Comment by Kakapio** [comment]
> As far as I can tell (please include the actual panic message in future) this is probably from failing to inverse a transform matrix containing 0 in debug mode? We likely need to special case the zero transform such that we don't end up inverting.
> 
> @Keavon / @Kakapio I struggle to see how this is relevant to a change in the pivot code.

[Here's the full output](https://pastebin.com/JvAL1yYq), I think. This should be the correct log.

**Comment by Keavon** [comment]
Can't currently reproduce.
