### ISSUE TITLE
Prod build appears stuck using latest release.

### ISSUE THREAD

**Issue by nobicycle** [GraphiteEditor/Graphite#1639]
`[user@tower frontend]$ npm run build --verbose 
npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@10.4.0
npm info using node@v21.6.1
npm verb title npm run build
npm verb argv "run" "build" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/home/user/.npm/_logs/2024-03-02T06_04_12_481Z-
npm verb logfile /home/user/.npm/_logs/2024-03-02T06_04_12_481Z-debug-0.log

> build
> npm run build-wasm-prod && vite build || (npm run print-building-help && exit 1)

npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@10.4.0
npm info using node@v21.6.1
npm verb title npm run build-wasm-prod
npm verb argv "run" "build-wasm-prod"
npm verb logfile logs-max:10 dir:/home/user/.npm/_logs/2024-03-02T06_04_12_851Z-
npm verb logfile /home/user/.npm/_logs/2024-03-02T06_04_12_851Z-debug-0.log

> build-wasm-prod
> wasm-pack build ./wasm --release --target=web`

No progress after 30 minutes.

System:
$ uname -a
Linux tower 6.6.16-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Feb 10 09:40:02 UTC 2024 x86_64 GNU/Linux

**Comment by Keavon** [comment]
Hmmm. Did you install all the necessary [documented](https://graphite.rs/volunteer/guide/getting-started/) prerequisites? Can you run a development build and serve from localhost?

**Comment by nobicycle** [comment]
@Keavon 
Yes,  from the frontend folder, I did (without errors):
$npm install
```
Changed 72 packages, and audited 399 packages in 11m

143 packages are looking for funding

```
$cargo install cargo-about

CPU  is 0% utilisation for the wasm process.
Where can I add --verbose to the call of wasm? Maybe that would help.

**Comment by 0HyperCube** [comment]
After the build process, do you have a `graphite/frontend/wasm/pkg` containing a wasm file? Do you have a `graphite/frontend/dist` folder? Or perhaps a `target/wasm32-unknown-unknown/release` folder?

Could you elaborate on what you mean by the "wasm process"? Is this wasm-bindgen or rustc or your browser running the wasm? Furthermore can you reproduce this if you update rust, npm, etc, run a git clean -X -d -f and rebuild?
