### ISSUE TITLE
Show working color modifications in the frontend

### ISSUE THREAD

**Issue by TrueDoctor** [GraphiteEditor/Graphite#164]
Currently ToolMessage::SwapColors and ToolMessage::ResetColors don't inform the frontend of their changes.

Todo: 
* Add a FrontendMessage::UpdateWorkingColors(primary, secondary)
* emit that message in the tool_message_handler.rs
* add the message type to client/web/src/response-handlers.ts
* register a listener for the message in Document.vue
* modify the working colors accordingly

Test cases:
* use the keyboard shortcut X to check the colors have been swapped
* click the swap and reset buttons below your color picker swatches

Comeplexity: 1
Involves: Editor (Rust), Frontend (Javascript)

**Comment by akshay1992kalbhor** [comment]
Can I try this?

**Comment by Keavon** [comment]
Absolutely! True Doctor assigned you to it. Post a PR (even if it's a draft PR) and we can also add the In-Progress tag to this issue for you also.

**Comment by TrueDoctor** [comment]
Yes I think this one should suit you really well, please let me know when you have questions and I'll be happy to guide you through

**Comment by akshay1992kalbhor** [comment]
I am a little intimidated now that I could not finish the last one, but the only way is through so going to try this one. Can you please give me deadline for this? Deadlines really help me work :)

**Comment by Keavon** [comment]
The sprint ends today/tomorrow (the 12th, whichever day that is for your time zone) at 16:00 UTC when we present for the Rust Gamedev Meetup, so if you have time to get your PR merged by then, it'll be checked off the Sprint 4 list.

Otherwise it will be bumped to Sprint 5 and hopefully be one of the first fixes completed for that sprint.

**Comment by akshay1992kalbhor** [comment]
OK that should help

**Comment by TrueDoctor** [comment]
> I am a little intimidated now that I could not finish the last one, but the only way is through so going to try this one. Can you please give me deadline for this? Deadlines really help me work :)

I can also offer pair programming if you have time

**Comment by TrueDoctor** [comment]
We do kinda have a bad track record with the complexity we assign to issues and what it actually takes to implement the feature but in this case I am pretty certain that there shouldn't be any unexpected obstacles

**Comment by akshay1992kalbhor** [comment]
> > I am a little intimidated now that I could not finish the last one, but the only way is through so going to try this one. Can you please give me deadline for this? Deadlines really help me work :)
> 
> I can also offer pair programming if you have time

I am definitely interested. How would that work?

**Comment by TrueDoctor** [comment]
> > > I am a little intimidated now that I could not finish the last one, but the only way is through so going to try this one. Can you please give me deadline for this? Deadlines really help me work :)
> > 
> > 
> > I can also offer pair programming if you have time
> 
> I am definitely interested. How would that work?

We get on the graphite discord, you start a screen share and I can help guide you through

**Comment by akshay1992kalbhor** [comment]
Cool. I will need sometime to read through the code and figure out what I am dealing with. When do you want to do it?

**Comment by TrueDoctor** [comment]
Whenever you have time. I have a few things scheduled for today but they will probably happen a bit later.
You should not need to read too much code beforehand but you are of course always welcome to do so. Ideally just ping me on discord when you are ready

**Comment by akshay1992kalbhor** [comment]
OK

**Comment by Keavon** [comment]
Closed by #180
