### ISSUE TITLE
Support rounded corners with the Rectangle node

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1642]
Currently it is possible to create a rectangle by inserting a rectangle node in the node graph ("Node Graph" button in top right corner then right click in graph and select "Rectangle"). However it is not possible to make the corners round.

An option for the border radius should be added to the properties (on the right when the rectangle node is selected) that allows for creating a rounded rectangle. Note that it is not possible to create a perfect arc using bézier curves, so an approximation will need to be used (like for the circle currently).

Here is the a screenshot of the current rectangle node for reference:
![Current rectangle node](https://github.com/GraphiteEditor/Graphite/assets/78500760/ec1f8569-1d73-47fa-988b-8059e9a8e611)

**Comment by skoriop** [comment]
Hi, I'd like to be assigned this issue.

**Comment by devharsh2k4** [comment]
Hey is it done? cause i want to get assigned

**Comment by Keavon** [comment]
@devharsh2k4 this is already in progress.
