### ISSUE TITLE
Artboard tool doesn't have snapping implemented

### ISSUE THREAD

**Issue by milan-sedivy** [GraphiteEditor/Graphite#1662]
Artboard doesn't support snapping, either it should be implemented or perhaps the option to turn on snapping should be disabled?

**Comment by Keavon** [comment]
Snapping should be implemented for the artboard, yes.

**Comment by Keavon** [comment]
@Sahilgill24 for tracking purposes can you please comment in this issue so I can co-assign it to you?

**Comment by Sahilgill24** [comment]
Hey @Keavon , was really busy with my acads that's why was not able to continue it properly

**Comment by Keavon** [comment]
@Sahilgill24 it's all good, it looks like Hypercube kindly finished it up for you so we'll get this merged soon. Feel free to keep contributing to the project if you're so inclined when you have more free time :)
