### ISSUE TITLE
Some tools send DocumentMessage::Undo instead of DocumentMessage::AbortTransaction when Aborting

### ISSUE THREAD

**Issue by milan-sedivy** [GraphiteEditor/Graphite#1663]
Example of a tool with this behavior is "SelectTool".

DocumentMessage::Undo stores the history step, which can lead to the deletion of a previously stored redo step see #1659 and related Pull request for more information.

**Comment by Keavon** [comment]
Was this resolved by #1664? If so, we can close this, but I'm not sure if that PR did indeed resolve it or if this issue's part was left unfinished.

**Comment by Keavon** [comment]
Presuming closed by #1664.
