### ISSUE TITLE
API for Embeddable Library and to be used by AI editors

### ISSUE THREAD

**Issue by sirinath** [GraphiteEditor/Graphite#1684]
Always consider API for library use cases and also use cases that this might be used in AI video editors too in the future.

**Comment by Keavon** [comment]
Hi, unfortunately I can't understand what this issue is requesting.

**Comment by sirinath** [comment]
Currently the focus is the editor.

Can a libGraphite be factored out so it can be used in own projects without the editor.

Maybe the libGraphite's API might be usable by AI assisted editors too which can do the editing my human prompts.

**Comment by Keavon** [comment]
In theory, we have architected our backend to operate independently of its frontend. But publishing an officially supported "libGraphite" as you mention, if it ever happens, won't be a priority for a very long time.
