### ISSUE TITLE
Using the procedural art engine as a library?

### ISSUE THREAD

**Issue by TheKnarf** [GraphiteEditor/Graphite#1692]
Let's say your making a game, and you do the art in Graphite, and then you want to import it into a game your writing in Bevy; is there a way to modify the art live as a part of your game? All of this procedural design workflow and node-based layers and stuff seems like it would be great if it could be embedded in the game itself and modified live.

**Comment by TrueDoctor** [comment]
Yeah, thanks for asking, this is definitely an intended use case and you can see some of the work towards that in the `graphene-cli` crate which provides a simple command line wrapper for the nodegraph. The system is definetly intended to be usable as a library.

**Comment by TheKnarf** [comment]
Maybe some documentation about this use-case could be added to the website? It also doesn't seem like the use of those crates have any documentation docs.rs on how they are ment to be used?

**Comment by Keavon** [comment]
You can find this on the public roadmap](https://graphite.rs/features/#roadmap): "Portable, embeddable render engine" (at the very bottom).

**Comment by 0HyperCube** [comment]
This currently isn't being worked on for the moment @TheKnarf. Perhaps we could look at something like Rive cross platform animations https://rive.app/blog/rive-renderer-now-open-source-and-available-on-all-platforms
