### ISSUE TITLE
Subpath::new_rect() creates cubic segments instead of linear segments

### ISSUE THREAD

**Issue by auberisky** [GraphiteEditor/Graphite#1696]
Hi,

The bezier-rs `Subpath::new_rect()` constructor creates cubic segments, but imho linear segments would be more fitting?

Thanks!

**Comment by mcargille** [comment]
Is this still relevant? Looking for a good issue to start contributing with

**Comment by Keavon** [comment]
@mcargille sure, this would be a quick and easy one to handle and should be pretty quick. After you have a PR open for this, let me know if you'd like help picking out a second beginner issue.

**Comment by Sidharth-Singh10** [comment]
PR #2109  fixes this issue.
