### ISSUE TITLE
Show artboard names in viewport

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1706]
Currently it is possible to rename an artboard by double clicking in the layer tree. However this change is not reflected in the viewport, where it is still titled "Artboard".
![artboard with incorrect name in viewport](https://github.com/GraphiteEditor/Graphite/assets/78500760/724224f1-1fb8-4eb8-8c43-edb72f09d90b)

See `impl GraphicElementRendered for Artboard` for the artboard rendering code. This change necessitates the passing of the name string into the graph execution context, whereas currently it is just visible as metadata on the document graph and so not sent to the actual node implementations at all. If the `ConstructLayerNode` got the layer name as input then it could apply the name to the passed in `GraphicElement`, which would involve storing the string in the `Artboard` struct and then retrieving that during rendering.

**Comment by ysrtyfn** [comment]
Hello, I would like to work on this issue. If it is OK, I can send a draft PR and start working.

**Comment by Keavon** [comment]
This should be available, so please open a PR for it, thanks!

**Comment by Keavon** [comment]
Closed by #1795
