### ISSUE TITLE
Contextually reactive user input hint system

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#171]
The status bar is designed to display live, reactive hints indicating all the current possible user interactions with the mouse and keyboard (or other input devices in the future). Right now the frontend has this hard-coded to show example actions that the Select Tool can perform when a layer is selected. This issue adds support in the editor backend for reactively determining the current inputs, given the current status of the tool's state machine, the selection, and other editor state. It then exposes the list of hints to the frontend for rendering. It may be useful to reference [this component](https://github.com/GraphiteEditor/Graphite/blob/master/client/web/src/components/window/status-bar/StatusBar.vue) in the Vue code for the usage of how they get rendered on screen. This will likely change somewhat to accommodate a consistent API (instead of magic example data). But this task is almost entirely Rust work, and if the developer who works on this is not comfortable with the web side, I can work on that aspect.

Progress:
- [x] Backend (#234)
- [x] Frontend (#388)

**Comment by TrueDoctor** [comment]
Things to do:
- Provide a formatting implementation for every key (this function should probably be in the input mapper)
- expose a function in the input mapper that takes an action list as an argument, iterates through all currently available actions, matches them up with keybinds and basically does this:
```rust
for (key, action) in keybinds.filter(|entry| actions.contains(entry.action)) {
  format!("{} {}", format_key(key), format_action(action))
}
```
- create a frontend message to update the hint list
- add some logic when to update the hint list

**Comment by Keavon** [comment]
@TrueDoctor this should be tagged as Started, right? Do you also have a branch or PR we could attach to this issue?

**Comment by TrueDoctor** [comment]
> @TrueDoctor this should be tagged as Started, right? Do you also have a branch or PR we could attach to this issue?

Made a draft PR
