### ISSUE TITLE
Fix Deep/Shallow selection regression

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1723]
At some point not that long after @0HyperCube helpfully rebuilt Deep/Shallow Select in 208e907fa4b561f28bc874211a43f4a762777157, it seems to have broken as a result of a regression ().

![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/0652b859-46b8-40e2-8104-791bd2d9d4ad)

Deep Select only selects the shallow group, not the deepest layer in the nested groups. Shallow Select's double clicking causes the double-clicked layer to disappear.

Maybe someone can bisect the Git history to find when that occurred (it was observed to be occurring prior to March, so Jan-Feb are the months to look). This would be a good issue for someone to find and fix.

**Comment by Tiger3018** [comment]
Done.
