### ISSUE TITLE
Audit and reclassify node catalog

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1735]
For each node:
- Standardize node and parameter names
- Classify into new category naming scheme (or remove entirely)
- Ensure input invariants are enforced (even when fed via the graph)
- Consider if it can be generalized and combined with other nodes

**Comment by TrueDoctor** [comment]
Can we add category for internal/experimental nodes which the user needs to opt in to see?
There are a bunch of nodes which currently confuse users but always removing them kills dev speed. I'd imaging something like a toggle in the preferences to opt into that experimental tag/group

**Comment by Keavon** [comment]
Sure, or even just a clearly named category like "Dev Use Only".

**Comment by Keavon** [comment]
Closed by e647ca9f91a5e823137122126fe9e980f65d62ea
