### ISSUE TITLE
(Question) What is the Cargo package of the desktop client?

### ISSUE THREAD

**Issue by hardBSDk** [GraphiteEditor/Graphite#1744]
I'm confused between `frontend/wasm`, `frontend/src-tauri` and `editor`, please document it.

**Comment by Keavon** [comment]
There is currently no Tauri client, that is old prototype code that's being replaced soon.

Do these sources of documentation help answer your question?

- https://graphite.rs/volunteer/guide/projects/
- https://graphite.rs/volunteer/guide/codebase-overview/code-structure/
- https://github.com/GraphiteEditor/Graphite/blob/master/frontend/README.md

**Comment by hardBSDk** [comment]
@Keavon I saw now that it need NodeJS in the build process, I recommend that you replace it by something that is better to packaging and cross-compilation (my case).

I suggest a Cargo package for the desktop client, like other Rust programs.

**Comment by Keavon** [comment]
Node.js is used for the frontend component of our architecture so that won't be possible until the far-future potential Xilem rewrite.
