### ISSUE TITLE
(Design suggestion) Replace GTK by a Rust GUI toolkit

### ISSUE THREAD

**Issue by hardBSDk** [GraphiteEditor/Graphite#1745]
I recommend egui or Iced.

**Comment by Keavon** [comment]
Thanks for the suggestion, but we don't use GTK either. We use the web at the moment, and will soon support desktop apps through Tauri.

**Comment by hardBSDk** [comment]
@Keavon The documentation say that GTK3 is needed, it's outdated.

https://graphite.rs/volunteer/guide/getting-started/

**Comment by Keavon** [comment]
I'm not familiar with Linux ecosystem dependencies but that is one of the required dependencies, I'm not sure what for though.

**Comment by hardBSDk** [comment]
@Keavon Probably a dependency of some crate (search for `gtk` in the dependency chain), the Ruffle emulator use GTK3 to show the GUI file picker.

**Comment by 0HyperCube** [comment]
@hardBSDk GTK is a dependency of tauri https://github.com/tauri-apps/tauri/blob/dev/core/tauri/Cargo.toml#L85.

There is no need to upgrade immediately as GTK3 is actively maintained https://gitlab.gnome.org/GNOME/gtk/-/commits/gtk-3-24 - but if you are interested in contributing to the tauri see https://github.com/tauri-apps/tauri/issues/7335.
