### ISSUE TITLE
Multi-column tool shelf

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#176]
Allow the user to expand the tool shelf into a two-column configuration by dragging the border between the tool shelf and viewport in the empty area below the tool buttons (should should have a guaranteed minimum space below, even when scrollbars are active).

**Comment by alezzacreative** [comment]
Hello, could this solution the team in Inkscape did for the upcoming version be convenient for graphite

https://user-images.githubusercontent.com/63913433/166314794-57487f22-59ee-4b9b-aa28-af789d4abcc9.mp4

when you resize the group of tools resize accordinly ( respecting the separators)

**Comment by Keavon** [comment]
Something like that could work in the future but we don't have a preferences menu yet, nor is there really a need to show and hide tools yet. Once we have a lot more tools, that may become more useful then. At the moment, tools are grouped into the General/Vector/Raster sections so resizing the columns of the tool shelf will do what's shown there by making each section wrap with its siblings.

**Comment by alezzacreative** [comment]
> Something like that could work in the future but we don't have a preferences menu yet, nor is there really a need to show and hide tools yet. Once we have a lot more tools, that may become more useful then. At the moment, tools are grouped into the General/Vector/Raster sections so resizing the columns of the tool shelf will do what's shown there by making each section wrap with its siblings. This feature is basically the CSS/JS for that column resizing and reflow.

Yes I understand I just needed to show the entire solution we ended up with for future referencen, it was subject of a lot of iterations between devs and us in the UX team to nail the desired flow ( GTK is a nightmare to work with)

**Comment by Keavon** [comment]
Understood, thank you for showing that off!

I think in the longer term, we'll have a whole lot of tools based on people's plugins from the plugin store. So managing that effectively will be pretty important!
