### ISSUE TITLE
Clicking a selected anchor should deselect all other selected points

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1774]
The only way to deselect all points, when all are selected, is with <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>A</kbd>. We want to be able to simply click (but not drag, and without <kbd>Shift</kbd> held) an existing selected anchor to replace the entire selection with that one point. Right now this requires either the deselect all shortcut, followed by clicking it; or <kbd>Shift</kbd>-clicking it and then clicking it again (without <kbd>Shift</kbd> held).

https://github.com/GraphiteEditor/Graphite/assets/4388688/092e80c2-5668-43a6-b9af-7d63cbb00ecc

**Comment by ysrtyfn** [comment]
Hello, if it OK, I would like to work on this. Please assign this task to me.

**Comment by Keavon** [comment]
@ysrtyfn yes, please begin and open a PR! This is actually a rather urgent issue so if you could aim to complete it before the weekend, that would be really helpful to us. Feel free to ask plenty of questions on our Discord if you're stuck. I'll assign this issue once you have a PR open. Thanks for volunteering!
