### ISSUE TITLE
Cannot rearrange layers in infinite canvas

### ISSUE THREAD

**Issue by adamgerhant** [GraphiteEditor/Graphite#1785]
Caused by parent being None, since the export node is not an actual node.

**Comment by 0HyperCube** [comment]
This is not due to the parent being None, but instead because you have disabled inserting layers as a child of the root @adamgerhant.
https://github.com/GraphiteEditor/Graphite/blob/5b6a2518e41b1dde12dde9ef9e2bc6f2207dcfaa/editor/src/messages/portfolio/document/document_message_handler.rs#L565-L568
