### ISSUE TITLE
CLI fails to build cause tokio needs `rt-multi-thread` feature

### ISSUE THREAD

**Issue by dzervas** [GraphiteEditor/Graphite#1798]
I tried running `graphene-cli` from the main branch as follows:

```bash
docker run -it rust
git clone https://github.com/GraphiteEditor/Graphite
cd Graphite
cargo run -p graphene-cli
```

and I got:

```text
root@015f96e932d6:/usr/src/Graphite# cargo run -p graphene-cli
   Compiling graphene-cli v0.1.0 (/usr/src/Graphite/node-graph/graphene-cli)
error: The default runtime flavor is `multi_thread`, but the `rt-multi-thread` feature is disabled.
  --> node-graph/graphene-cli/src/main.rs:22:1
   |
22 | #[tokio::main]
   | ^^^^^^^^^^^^^^
   |
   = note: this error originates in the attribute macro `tokio::main` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `graphene-cli` (bin "graphene-cli") due to 1 previous error
```

Adding the `rt-multi-thread` feature to the `tokio` dependency in the cli's `Cargo.toml` fixed it

I'm unsure though if running the main branch was a good idea - should I make a PR to fix this?

**Comment by Keavon** [comment]
Graphene CLI is just a testing utility that isn't currently a maintained, user-facing product (although someday it will eventually become that). I'm going to close this because there's nothing particularly actionable at this moment.
