### ISSUE TITLE
Fix boolean operations with several subpaths

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1803]
When one of the layers in the boolean operation has several subpaths, the result is not correct. This is due to Paper.js returning an incorrect result; for example:
```js
console.info(booleanOperation("M0,0 L100,0 L100,100 L0,100Z", "M50,50 L60,50 L60,150 L50,150Z M70,50 L80,50 L80,150 L70,150Z", "unite"));
```
![boolean result](https://github.com/GraphiteEditor/Graphite/assets/78500760/e5c70dd3-e222-4ea9-834b-24c5fecd34ea)
Red is the first path, green is the second path, white is the result (note the added curves in the union).

**Comment by Keavon** [comment]
I wonder if we can preprocess this to work around the Paper.js issue?

**Comment by 0HyperCube** [comment]
Looking at this again, I think we should be using the [compound path](http://paperjs.org/reference/compoundpath/) rather than the [path](http://paperjs.org/reference/path/).

**Comment by Keavon** [comment]
Oh, perhaps that's it! I didn't ever dig too deeply into the Paper.js docs so I wasn't aware of that. Would you like to try a stab at fixing the code? Or I can try it out today.
