### ISSUE TITLE
Transparency loss when setting working colors from Rust

### ISSUE THREAD

**Issue by TrueDoctor** [GraphiteEditor/Graphite#181]
When setting the working colors from the rust code,  the colors are set to 100% opacity.
To reproduce:
Set a transparent color in the color picker and then press shift + x to swap the colors.
@akshay1992kalbhor has indicated interest in working on this.

**Comment by Keavon** [comment]
@akshay1992kalbhor if you'd like to work on this, just let us know. (GitHub requires you comment in the thread before we can assign the issue to you.)

**Comment by akshay1992kalbhor** [comment]
Yes i want to. Will start in a couple of hours

**Comment by Keavon** [comment]
Awesome, glad to hear it! Please reach out if you're at all stuck or confused. I assigned you the issue and set it to In-Progress. If you end up not starting on the issue soon, please comment and I can remove the In-Progress label so its status is more clear.

**Comment by Keavon** [comment]
Closed by #212
