### ISSUE TITLE
Deep Select mode of the Select tool currently doesn't do anything

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1831]
This worked in the past but after the various node graph representation changes, it currently doesn't select anything when you click with the Select tool with Deep Select mode active. You can't click to select a group or a boolean operation layer, and you can't drag them either. Double-clicking also doesn't deepen the selection by a level. However, at least <kbd>Ctrl</kbd>-clicking a layer in order to temporarily deep select does successfully deep select.

Now that we have #1829, the shallow select mode will actually be a lot more useful too, once it's working again.

**Comment by Umer-K-PersonOOO** [comment]
Fixed!
