### ISSUE TITLE
Populate the Properties Panel with SVG shape properties

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#186]
This is a temporary approach that allows modifying shape fill and stroke color, stroke width, etc. before we have a proper system for populating the layer's node properties, which is blocked on big architectural decisions. This is a quick and dirty feature to make the artwork creation process more powerful in the short term.

**Comment by KeatonTech** [comment]
I'd be interested in taking this. Any guidance on what the UI should look like?

**Comment by Keavon** [comment]
@KeatonTech this is a pretty large feature that touches all areas of the frontend and backend and document system, so it might be better to do a few small/medium-sized tasks before tackling this one. However you're definitely still welcome if you prefer jump straight into the deep end.

The UI should look like this (top right panel):
![](https://camo.githubusercontent.com/68f0ba1500ee6d6f27828c73cadbd3b6c7053560555af8b46ebb4ed400e096fb/68747470733a2f2f66696c65732e6b6561766f6e2e636f6d2f2d2f4e65696768626f72696e6752656c6961626c65436f6e7572652f636170747572652e706e67)

**Comment by KeatonTech** [comment]
I was thinking of expanding the LayerData trait with a new function like:

```rust
pub trait LayerData {
  // ...
  fn get_properties(&self) -> HashMap<&'const str, Property>;
  // ...
}
```

Where `Property` is defined with something like:
```rust
struct Property {
  name: String;
  type: PropertyType;
  ui_group: UiGroup;
  current_value: Option<PropertyValue>;
}

/* This should be the same enum that eventually gets used to specify graph input and output types. */
enum PropertyType {
  String,
  Boolean,
  Number,
  // ...
}

enum UiGroup {
  Blending,
  Origin,
  Transform,
  Fill,
  Stroke,
  // ...  
}

enum PropertyValue {
  String(String),
  Boolean(bool),
  Number(f64),
  // ...
}
```

(Note that this rust code might not be 100% syntactically correct, just using it as pseudocode).

Then there could be a new SetLayerProperty action that modifies one of these by name. The Editor layer or the Vue layer could move from a hashmap to a list of groups of properties, arranged however the UI wants to arrange them.

**Comment by Keavon** [comment]
Closing this stopgap issue because the full Properties Panel is being implemented now by @mfish33 and this temporary approach is no longer necessary.
