### ISSUE TITLE
Export : Missing artboard names

### ISSUE THREAD

**Issue by axel37** [GraphiteEditor/Graphite#1883]
When exporting a project with multiple artboards, their names don't appear in the `Bounds` menu :

![A screenshot of the editor with the export menu open. The export menu shows multiple artboards named "untitled", which does not correspond to the artboards' actual names.](https://github.com/user-attachments/assets/b42e64a0-ba0b-48ad-86b9-7e3af17e461c)

Instead, each artboard is named : `Artboard : Untitled x` (with `x` being a number).

This makes it hard to know which option to select.

___

For some context : I'm using [Graphite on the web](https://editor.graphite.rs/) to create sprites for a video game, and it's very handy to be able to create one artboard per sprite without having to create multiple projects !

**Comment by Keavon** [comment]
Thank you for this report, you've noticed something we've overlooked. Artboard naming was added sometime after building that menu and it seems we forgot to update it with the names.

**Comment by Keavon** [comment]
Sure thing, glad to help! It's live on https://dev.graphite.rs and will be on the next https://editor.graphite.rs release in about half an hour.
