### ISSUE TITLE
Allow multiple output wires from the top of a layer stack

### ISSUE THREAD

**Issue by tschundler** [GraphiteEditor/Graphite#1886]
When duplicating something, it seems to copy the whole tree. Edits to the original do not affect the copy. Most of the time, I suspect that is what users want.

But I was thinking I could use this like Blender geometry nodes and use the original data multiple times. The graph seems to require one input to one output? So there doesn't seem (to me) to be an intuitive way to duplicate geometry - eg transform a shape two different ways and apply a boolean while keeping just one set of original shapes.

**Comment by tschundler** [comment]
Example where I started experimenting to create a wiggly line graphic design element and was hoping to use such a feature: 
[Worm.graphite.zip](https://github.com/user-attachments/files/16475250/Worm.graphite.zip)

I wanted to experiment with sizes and angles. (in the end I used CAD software)

**Comment by Keavon** [comment]
Right now this is possible if you run it through an Identity node (basically a passthrough, or the "reroute" dots in other node graph apps).

https://github.com/user-attachments/assets/35182b8b-c2cd-4183-8dcd-837a664fd9ff

The problem you encountered is that layer stacks don't permit multiple outputs from the top connection. We'll fix that.

**Comment by Keavon** [comment]
[Worm Cleaned Up.graphite.txt](https://github.com/user-attachments/files/16478325/Worm.Cleaned.Up.graphite.txt)

By the way, here's your artwork with the graph cleaned up. I did that by dragging around layers while holding <kbd>Shift</kbd> to move the whole layer chain of nodes around to organize things. (An auto-layout system is currently in development.)
