### ISSUE TITLE
Duplicate the selected layers

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#189]
Ctrl+D to duplicate the selected layers.

This should be a relatively simple task purely touching the Rust codebase. If you're interested in this issue, we can answer questions and write up a guide of steps to implement this feature.

**Comment by tillarnold** [comment]
I'd be interested in taking this task.

**Comment by Keavon** [comment]
Perfect, I assigned it to you @tillarnold. @TrueDoctor, would you be able to describe what this task will involve? We don't need layer offset for the duplicated or pasted layer.

**Comment by TrueDoctor** [comment]
I'm nor sure how this can be implemented cleanly, the easiest way would be to store a clipboard in the backend and manipulate it through operations but this is far from ideal. The other place to store these would be the editor, but until we have a history system setup we would need to resort to sending layers directly wrapped as operations which is not really idiomatic either.
I don't expect you to understand half of what I just said, It is also mean as a question for @Keavon

**Comment by Keavon** [comment]
Let's just do the duplicate part for now, then we can evaluate what is involved in the copy/paste part. @TrueDoctor

**Comment by TrueDoctor** [comment]
The easiest way to implement duplicate functionality is to add an Operation `Operation::DuplicateLayer{path: Vec<LayerId>}`.
That operation then just clones the layer to the same folder it resides in

**Comment by Keavon** [comment]
@tillarnold are you on the Discord server for Graphite yet? That's typically the way we onboard new contributors and provide an introduction to the code, either through a chat or voice call format. If that would be beneficial for your understanding, since I realize this may be confusing or vague without any context in the backend codebase. Or if you're the kind of person who's great at just reading through code files to orient yourself, that's also great. Discord is most commonly the easiest way to help you get up to speed but if that's not your thing, we want to help remove friction and confusion whatever it exists on any platform. Please let me or @TrueDoctor what would be best to help us help you succeed.
