### ISSUE TITLE
Refactor Vue input components with `v-model` to support input and output

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#190]
Currently the Vue components for input widgets are built, but can't be used for the back-and-forth with the backend API. When I wrote them, I didn't fully understand Vue's intended approach, but @FuriouZz has since informed me about [v-model](https://v3.vuejs.org/guide/migration/v-model.html). This issue involves going back to make some small refactoring changes so the widget components can be used by their parent components in a way that communicates with the Rust backend.

Blocking #184 which is an important feature for Sprint 5.

**Comment by Keavon** [comment]
@FuriouZz would you be willing to take this on? I can assign it to you if so. I think, since it's mostly just cleanup, it shouldn't be too time consuming.

**Comment by FuriouZz** [comment]
I take it! 😊
