### ISSUE TITLE
Node graph better organization

### ISSUE THREAD

**Issue by axel37** [GraphiteEditor/Graphite#1910]
I'm using graphite with multiple artboards in a single project, and the node graph is starting to get crowded :

![An overview of a cluttered node graph](https://github.com/user-attachments/assets/d7b98a11-75d6-4039-abcb-c6b50cde4ce5)

At this point, manual organization of nodes is tedious, and needs to be done regularly to account for new nodes.

### Automatically placement is messy, some nodes are placed on top of each other :

New nodes aren't placed in the most convenient of manners, and often need to be manually moved before being able to work with them :

![Nodes being placed on top of each other](https://github.com/user-attachments/assets/70991eb7-5c88-467c-9ad2-d969d0576932)

### New tools to add ?

Some additional features might make working with the node graph more convenient, such as :

- A way to group nodes into collapsible folders
- A way to quickly hide/show nodes based on selection

___

I found two related issues : #1820 and #1819 

#1820 lists the following shortcut which is indeed very useful : `Drag to move node (shift to drag row)`

**Comment by Keavon** [comment]
This is the focus of @adamgerhant's summer-long intern project. If you use dev.graphite.rs, some of its improvements are currently live and more are in-work.

**Comment by Keavon** [comment]
Also, you can hold Shift while dragging a layer to move it's upstream nodes along with it. Just a little convenience option that may be of help to you.
