### ISSUE TITLE
Set integer ruler increments in the Node Graph

### ISSUE THREAD

**Issue by adamgerhant** [GraphiteEditor/Graphite#1927]
When the node graph is open, the ruler increments should be rounded to a whole number. This may require calculating an offset and/or custom tick spacing to ensure the ticks are aligned when the zoom is changed.
![chrome_EGt9ReU4b0](https://github.com/user-attachments/assets/a15abe3e-e31d-4ba9-8382-62689d8b3539)

**Comment by Keavon** [comment]
@hydrobeam could you please leave a comment in this issue? GitHub requires you comment here so I can assign you as the person who completed this issue. Thanks!

**Comment by hydrobeam** [comment]
Sure :)
