### ISSUE TITLE
Resizable text boxes and text editing features

### ISSUE THREAD

**Issue by starlord-brazil** [GraphiteEditor/Graphite#1960]
Hello Graphite Community,

I'm exploring the capabilities of Graphite and am particularly interested in enhancing the text editing features within the software. I'm looking for a way to implement resizable text boxes where the text adjusts automatically to fit the size of the box. Additionally, I'd like the ability to configure line spacing within these text boxes. Could you provide insights or guidance on how to develop these features, or is there already work underway to integrate such functionalities into Graphite? Any pointers or collaboration on this would be greatly appreciated!

Thank you!

**Comment by 0HyperCube** [comment]
Presumably moved to https://github.com/GraphiteEditor/Graphite/discussions/1963. I'll answer there.
