### ISSUE TITLE
Incorporating Print-Specific Features: Measurement Conversion and PDF Export Capabilities in Graphite

### ISSUE THREAD

**Issue by starlord-brazil** [GraphiteEditor/Graphite#1961]
Hello Graphite Developers,

I am currently working on projects intended for print and was wondering if there are any plans to include features that would allow users to switch measurement units from pixels to millimeters. Additionally, are there any developments towards integrating direct printing capabilities or generating PDF files from within Graphite? These features would greatly enhance the tool's utility for print-focused workflows. Any updates or tips on how to approach these enhancements would be highly appreciated.

Thank you!

**Comment by Keavon** [comment]
Moved to #1962, by the looks of it.
