### ISSUE TITLE
Incorrect pen tool overlay when placing a second anchor

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1984]
When drawing a new path with the pen tool, the square overlay for the first anchor disappears when you are placing the second anchor. This should not happen.

Another regression introduced by #1946.

**Comment by adamgerhant** [comment]
Since the vector data the editor uses to draw the overlays comes from the render output through click targets, this will require creating a click target without any segments. Not sure how this is possible or previously done.
