### ISSUE TITLE
Nudge the selected layers around the canvas with the arrow keys

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#201]
The arrow keys nudge (move) the selected layer(s) by one canvas pixel. When the <kbd>Shift</kbd> modifier key is held down, the nudges go in increments of 10 canvas pixels.

This is probably a good first issue to get acquainted with some concepts in the Rust backend. Please reach out to @TrueDoctor here or on [Discord](https://discord.graphite.design) for in-depth instructions to help you get a feel for the code that this touches.

**Comment by henryksloan** [comment]
I've started working on this.

**Comment by Keavon** [comment]
This is blocked on the inability to transform layers directly, rather than just folders.

Some discussion from Discord:

> @henryksloan: Operation::TransformLayer seems to act on Folder layers; is that the wrong way to move an individual layer?

> @TrueDoctor: That is a shortcoming of the current design. We already have a fix, it just needs to get implemented.

**Comment by Keavon** [comment]
@henryksloan you should be unblocked now courtesy of the swift work of @0HyperCube.
