### ISSUE TITLE
Can't import SVGs with import menu or dragging files.

### ISSUE THREAD

**Issue by paulwrath1223** [GraphiteEditor/Graphite#2024]
First of all, you guys are awesome, discovered you guys from your Open Sauce booth, and I've been a fan since!

Using Ubuntu 24.04, trying to import an SVG by dragging or from the import menu does nothing. 
Tested with the graphite logo stolen right off your website.

However, when I copied the file and pasted it in the document, it works fine.

The only noticeable thing that happens when you try to import an SVG is that it says 'layer has no properties' on the right. (see attached) 

![image](https://github.com/user-attachments/assets/60d92887-8d31-497d-9c4c-cc585b57510a)

**Comment by Keavon** [comment]
Hey, thanks for visiting us at Open Sauce and mentioning that's where you found us!

This bug is probably already fixed. Can you try it at https://dev.graphite.rs ? We're preparing a new deployment very soon because it's been a month or two since the last release. Confirming if this is resolved would be helpful, thanks!

**Comment by paulwrath1223** [comment]
@Keavon

I didn't even know there was a dev version, but yeah it's fixed there and also runs **way** faster. I didn't mention the low and stuttery FPS before because I figured it was just a problem with Linux WebGPU implementation, but wow this is so much nicer.

Thanks for the help, closing the issue.

**Comment by Keavon** [comment]
There's been a lot of improvements recently! We're squaring away a few regressions and then releasing very soon. If you get the chance to help test for regressions between the versions, please report any that you find. Thanks!

**Comment by Keavon** [comment]
The new release went out a couple days ago, by the way! But do feel free to keep using `dev` instead of `editor` to help us test for regressions.
