### ISSUE TITLE
Improved Node Graph support for user created nodes.

### ISSUE THREAD

**Issue by adamgerhant** [GraphiteEditor/Graphite#2043]
It should be possible to select a group of nodes, and then "group" them into a single node with a network implementation of those nodes. It should also be possible to change the number, order, and names of inputs/outputs. It could also be useful to "ungroup" a node. Once #2042 is complete, it should also be possible to change the annotated types for the inputs, as detailed in #2069

**Comment by Keavon** [comment]
This will also be an important part of making lambdas more useful and approachable.
