### ISSUE TITLE
Select Tool: Add a bounding box around the selected layers

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#207]
We can do this temporarily with the "working layers" system before we have the proper overlays system post-0.1. This clarifies to the user which shapes are actually selected.

**Comment by Keavon** [comment]
This is probably (soft?)-blocked on #207, unless I'm wrong (@TrueDoctor or @pkupper, would you know if that's the case in more detail?)

**Comment by AyeTbk** [comment]
I will do this one
