### ISSUE TITLE
Path tool point nudging should be in document coordinates, not viewport coordinates

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#2083]
If you select a point using the Path tool and nudge it to the right by 10 units with <kbd>Shift</kbd><kbd>Right Arrow</kbd>, starting at 100% viewport zoom but then zooming to 200%, you'll notice it takes two presses of <kbd>Shift</kbd><kbd>Left Arrow</kbd> to return back to its starting place. That's because it currently is moving relative to the viewport coordinates, but it should always work relative to the document coordinates so 10 units to the right means the same thing regardless of the current level of zoom. It also shouldn't be in the layer's local coordinate space, where a shape that has a 0.1 scale factor would take 10 times as many presses to travel the intended distance. The Select tool's nudging can be referenced for this, because it works correctly in document space (not layer-local or viewport space).

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Keavon** [comment]
@November-6 can you please comment here so GitHub allows me to assign you as the person who completed this issue?

**Comment by November-6** [comment]
Sure. Thanks!
