### ISSUE TITLE
Overlapping widgets in file->preferences menu

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#2103]
The file->preferences menu looks like:
![preferences menu](https://github.com/user-attachments/assets/eee182f8-36c5-4157-b3a8-e4a4c4456f92)
It has some overlapping widgets which are most likely undesired. Introduced by https://github.com/GraphiteEditor/Graphite/commit/de366f951424fcdf4463a419db3fa659910fabfd.

**Comment by rajiknows** [comment]
can you assign me this issue ,  we just need to fix the CSS in the dialogue component

**Comment by RounakJoshi09** [comment]
Hi @0HyperCube , I have figured out the place , where the CSS have gone wrong , and fixed this in PR #2104. Actually the problem was, that the elements in the dialog was not acquiring whole space available, which is necessary for proper use of width.

**Comment by 0HyperCube** [comment]
Resolved by https://github.com/GraphiteEditor/Graphite/commit/99cf8f0c4f91a051b59fc2c9e5cc6c7417bdd74b.
