### ISSUE TITLE
Support for closing document tabs

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#211]
Click the X button in a tab to close it. Also <kbd>Ctrl</kbd><kbd>W</kbd> closes the current tab (warning: you can't test this yet, it'll close your browser tab also). This needs a confirmation to prevent loss of work. It also needs to handle what happens when all tabs are closed, perhaps for now that should work by automatically creating a new tab after closing the last tab. This feature might require the switch from document tab indexes to IDs in order to prevent the mutation of tab ordering from causing bugs and headaches.

**Comment by akshay1992kalbhor** [comment]
I am going have go at this
