### ISSUE TITLE
Math node for running custom expressions with A and B

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#2115]
The new maths parser introduced in #2033 is currently only utilised to immediately evaluate expressions in number inputs.

To expand its utility, a new node should be introduced to run an expression during the runtime of the graph. In future, this node could take inputs from the graph. However this is blocked on implementing nodes with variadic inputs.

**Comment by rajiknows** [comment]
hi @Keavon  , I'm interested to picking it up , could you please assign it to me .

**Comment by Keavon** [comment]
@rajiknows thanks for your interest! We do issue assignments near the end of the PR lifecycle now, so we'll assign it once you have a working PR that's looking like it has progress towards being merged. Good luck and thanks!

**Comment by jacinyan** [comment]
Hi @Keavon, going through the discussion I can see there should be an working PR soon. However, I was wondering if I can try to also contribute regardless of whether mine will be accepted at the end of the day. Thank you 😄

**Comment by jacinyan** [comment]
> @jacinyan Go ahead, and sorry if I’m blocking you. I got really busy with a college event. I’ll start working on this soon. Meanwhile, if you successfully solve it, please raise a PR.

No, no no definitely not, and we might probably go with co-authoring if you interested.
