### ISSUE TITLE
Keep selection when clicking in properties after creating text

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#2127]
- Create a new text box
- Type something
- Attempt to modify something in the properties of the newly added text layer (e.g. change the fill colour)
- The layer is deselected so the properties disappear.

It would be nice to keep the properties around when the user is trying to edit them.

**Comment by aabha25** [comment]
Hi @Keavon , I’ve looked into the issue and would be happy to work on it. I’ll open a PR soon!

**Comment by Sidharth-Singh10** [comment]
PR #2144  fixes this issue.
