### ISSUE TITLE
Drawing new shapes creates multiple selection history states

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#2137]
- Create a layer (e.g. with the rectangle or polygon tool)
- Go back in the selection history <kbd>Alt</kbd> + <kbd>[</kbd>
- Observe how the rectangle or polygon node is selected.

This is not the desired behaviour. We would expect the selection that was made before drawing the layer to be restored.

**Comment by bakayu** [comment]
fixed by #2138
