### ISSUE TITLE
Resizing an artboard by its top/left edges should keep its content stationary

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#2150]
Using the Artboard tool to resize an artboard from the top or left edge makes it shift its contents in canvas space, which isn't the desired behavior. It does this because the content is positioned in artboard space, so the Artboard tool needs to run special logic when resizing a top/left edge to compensate for the reverse of this, making the content translate by the inverse of the artboard edge resizing. The easy but bad way of doing this is adding a Transform node directly before the Artboard node. The better way is to loop through each layer that's a direct child of the artboard layer and apply a translation to it just as if the user had dragged the layers manually.

https://github.com/user-attachments/assets/492a6672-9ec2-4590-8b61-6a288214fe25

**Comment by ayushpatil2122** [comment]
i want to work on this issue

**Comment by Keavon** [comment]
@ayushpatil2122 go for it, and open a PR when you have something functional!

**Comment by pratikagr** [comment]
This issue is fixed!
