### ISSUE TITLE
Copy and paste layers

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#218]
Copy the selected layers and paste copies of them. The MVP for this feature is basically the same as duplication (#189), but not instant (you can copy, then paste later). If you copy layers then delete some of what you had copied, the paste will still recreate those deleted layers. The paste operation should preserve their order from top to bottom of the stack, but they should all be placed at the top of the current folder (which is presently just the root until we get folders working in the frontend). A copy buffer will need to be introduced, @TrueDoctor thinks in the editor backend is probably cleanest. This will later evolve or be replaced to support actual nodes (layers) in the node (layer) graph. Once #100 is merged, a helpful addition beyond the MVP for this issue will involve checking if the pasted layer is currently visible in the viewport. If so, paste in the same place where the layers were copied from. If not, paste in the center of the viewport.

**Comment by Keavon** [comment]
@tillarnold would you like to follow up #189 with this? Hopefully the description provides come clarity for you. It shouldn't be blocked, except the last two sentences which is blocked on #100.

**Comment by tillarnold** [comment]
Yeah I'll do this one.

**Comment by Keavon** [comment]
@tillarnold would you like any help getting started or continuing with your progress on this feature? I'd be more than happy to lend a hand.
