### ISSUE TITLE
Switch document tabs to work based on document ID not index

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#225]
This is required for #195 and will also simplify the code, where specific complexity was introduced to make indexes work correctly with closing tabs in #215.

**Comment by akshay1992kalbhor** [comment]
Can I work on this?

**Comment by Keavon** [comment]
@akshay1992kalbhor I marked this again as Available but I'm keeping it assigned to you. Please let me know when you have actually started writing code (and submit a draft PR) then I'll switch Available to In-Progress. In the meantime, if anyone else wants to take this assigned issue, I'm happy to reassign it (as is the case with any issues listed as Available but assigned, that means the work has not begun yet so it can be reassigned to anyone who's interested in starting on it sooner).

**Comment by psuong** [comment]
@Keavon forwarding this from the discord, to state I'd like to try this.
