### ISSUE TITLE
Pen Tool's newly created layer does not get auto-selected in the Layer Tree panel

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#227]
All the other tools replace the Layer Tree's selected layers with the newly created layer, but the Pen Tool does not do this and should.

**Comment by TrueDoctor** [comment]
TODO: go into `core/document/src/document.rs` scroll to the bottom and compare the add circle operation with the pen operation and add the selection message.

**Comment by kastenbutt** [comment]
I'd like to do this :)

**Comment by Keavon** [comment]
Awesome, thanks @kastenbutt! This is a nice and simple task but it gets you the chance to poke into the code and look around. Please reach out to @TrueDoctor or anyone else on the team for an introduction, including a voice call on Discord if you're interested in having a bit of an orientation or pair programming.

**Comment by Keavon** [comment]
Closed by #235.
