### ISSUE TITLE
Modifier keys get stuck when switching away from the Graphite browser window/tab

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#237]
The Shift, Ctrl, and Alt (modifier) keys get stuck when you use those keys to switch away from the browser window or tab running Graphite (for example, Alt-Tabbing). Then when you try to, for example, draw with a shape tool, it will get stuck in proportional scaling (Shift) and/or centered scaling (Alt). This also messes with the viewport keyboard shortcut navigation behavior (from #229). I believe the solution is to check the state of modifier keys any time that any input is processed and reset them to their current state, because the browser should be reporting the correct (non-stuck) value but we are only listening for modifier key state when modifier keys, rather than all forms of input, are received.

**Comment by AyeTbk** [comment]
I can work on this.
