### ISSUE TITLE
Rearranging layers with hotkeys

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#238]
<kbd>Ctrl</kbd><kbd>[</kbd> lowers the selected layer(s) in the stack, <kbd>Ctrl</kbd><kbd>]</kbd> raises, and the <kbd>Shift</kbd> modifier raises the selected layer(s) all the way to the top or bottom. Raising and lowering is constrained to the folder for now. Leave a `// TODO` for handling the case where layers from multiple separate folders or depths in the folder hierarchy are selected when trying to raise/lower.

**Comment by ajweeks** [comment]
I'm going to take a stab at this one 🙂
