### ISSUE TITLE
Any way to provide financial support?

### ISSUE THREAD

**Issue by vultix** [GraphiteEditor/Graphite#240]
Graphite is incredibly promising, thank you to everyone for your hard work bringing it to life!

I, and I'm sure many others, would love to support this project, but don't have the time to contribute code at the moment.  Is there any way for us to provide financial support, using a tool like GitHub Sponsors or Patreon?

**Comment by Keavon** [comment]
I figured that the project is at too early a stage for people to be interested in supporting financially. However I can definitely look into it and see what it would take to set that up, and where the funds can go to support development and pay expenses (domain names and infrastructure costs, an upcoming trademark application, etc.). I'll follow up with this in a few days once I've done some research.

**Comment by Keavon** [comment]
It might be a few months at minimum until we can set this up. But in the meantime, it would be useful to collect some information from interested people about what they might be willing to contribute. If you and other such people wouldn't mind commenting:

* How much you'd be willing to contribute (include the currency please)
* One-time or monthly
* Which of the following would you be able to support through: PayPal, Patreon, GitHub Sponsors?

Based on this information, it can hopefully help me prioritize this. I'm looking at what it would take to set up an LLC or a foundation and a bank account, etc. which is likely needed for the future of the project but will cost some money, which donations at this early stage probably won't cover yet. If I did it with a personal bank account, there are tax implications I'd prefer to keep separate from myself.

**Comment by Keavon** [comment]
Hello! Now it is possible to sponsor the project through my [GitHub Sponsors page](https://github.com/sponsors/Keavon). This will go towards infrastructure and other project management-related costs that I have incurred. Thanks for inquiring about it!
