### ISSUE TITLE
Unite web build systems (WebPack for WASM bindings and Vue CLI for frontend)

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#29]
See the [readme](https://github.com/Keavon/Graphite/blob/master/README.md#running-the-code) on how we currently have two separate build systems:

The Vue.js frontend builds with Vue CLI using the commands `npm run build`, `npm run serve`, and `npm run lint`.

The wasm-bindgen infrastructure builds with WebPack using the commands `npm run webpack-build` and `npm run webpack-start`.

(See [package.json](https://github.com/Keavon/Graphite/blob/master/web-frontend/package.json))

We should probably move both over to WebPack in some way that allows the built WASM modules to work in the Vue app. I am positively abysmal at wrangling build systems so I need help from somebody who has knowledge of this.

It would also be great if we can upgrade to WebPack 5, but I had to downgrade because of [an incompatibility](https://github.com/vuejs/vue-cli/issues/5986) that I ran into (but perhaps I was just doing something wrong).

Bonus: help improve the reliability of the development environment in VS Code (and perhaps other editors, if that's of interest to people). It's currently very un-robust. Configurations for linters, auto-formatting, code completion in Vue files, tidying up build environment related things all around the project, etc.

**Comment by AngelOnFira** [comment]
If you can assign this to me, I'm going to start working through it :100:

**Comment by Keavon** [comment]
👍 Thanks for volunteering! Let me know if you have any questions.

**Comment by Keavon** [comment]
It would also be fantastic if we can get [vue-svg-loader](https://vue-svg-loader.js.org/) working (it's currently included in `package.json`'s `devDependencies` but I couldn't get it to work). That way we can store, edit, and version SVG icons as separate files but place them inline at build time.

**Comment by TrueDoctor** [comment]
@AngelOnFira do you have experience with WebPack in regard to things like extensibility of the wasm boilerplate?
We might need to modify that in the future to get multi threading working. + What advantage does WebPack provide over just loading the wasm module manually?
