### ISSUE TITLE
Fix console warning when releasing a mouse press inside the canvas started outside

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#291]
Click somewhere outside the canvas (in the Vue part of the UI) and drag your mouse into the document canvas, then release the click. You'll see the following error show up each time in the JS console.

![](https://files.keavon.com/-/LegalHilariousGazelle/capture.png)

**Comment by 0HyperCube** [comment]
This also happens when dragging the scrollbars on #328
