### ISSUE TITLE
Design the render engine architecture

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#30]
Let's kick off this module with a meeting on Discord next weekend (Feb 27 or 28).

Before then, I am going to write up documentation on how the node system in Graphite behaves (so it isn't all just living in my mind) so we can glean the necessary technical requirements.

Then we can discuss what Rust/WGPU architecture will make this work.

Pick times you are available to meet: http://whenisgood.net/qkgaq4k

**Comment by maroider** [comment]
> Pick times you are available to meet: http://whenisgood.net/qkgaq4k

I can't select a timezone with that link.

**Comment by Keavon** [comment]
Thanks for bringing that to my attention, I edited the form to allow time zones. You should be good to go now, select your timezone before you enter your times.

**Comment by Keavon** [comment]
I am closing this because we are no longer immediately pursuing a render engine, in lieu of doing a vector-only approach for the 0.1 release. I might not be around this weekend but if I am, I'll ask everyone on Discord to see if we are able to meet to discuss the core application state architecture and its WASM interface with the Vue frontend.
