### ISSUE TITLE
Frontend color selection response is prone to infinite loops

### ISSUE THREAD

**Issue by henryksloan** [GraphiteEditor/Graphite#304]
From #300:

The [eyedropper tool] color update is implemented using FrontendMessage::UpdateWorkingColors as opposed to SelectPrimaryColor. That is because using the former doesn't update colors on the frontend. Adding UpdateWorkingColors to the handler for SelectPrimaryColor causes an unresponsive infinite-loop on the frontend. This is because SwatchPairInput registers a response handler for ResponseType.UpdateWorkingColors but also watches primaryColor and secondaryColor, mapping changes to SwatchPairInput.update{Primary | Secondary}Color. Those two functions each the respective WASM functions, which in turn dispatch the color selection messages, causing an infinite loop.
In the future, I think this infinite loop should be avoided by removing the watches and instead add callbacks to ColorPicker. We should only be dispatching the Select...Color messages when the frontend (i.e. the user) updates the colors. In fact, as it currently is, the response handler for UpdateWorkingColors always dispatches redundant calls to SelectPrimaryColor and SelectSecondaryColor.

Once the looping tendency is fixed, these select messages should also update the frontend colors.

**Comment by TrueDoctor** [comment]
The ideomatic thing to do would be to only emit the set color messages upon user input and not upon a state change, so pretty much as you described
