### ISSUE TITLE
Grid snapping system

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#318]
We will want a grid system for snapping.

Longer-term, here are some further features that will encompass the full grid system:

> It should also be displayed over the canvas in user-configurable ways.
> 
> We'll want a concept of document pixels for precise pixel alignment and snapping, drawing pixel art, and previewing a zoomed-in document at its export resolution. (Even though this concept exists for measurements, it does not restrict the rendering of the document at any arbitrarily high resolution, because of Graphite's concept of resolution agnosticism.)
> 
> We will want both pixel and real-world (metric/US) units of measure at arbitrarily large or small scales (millimeters to miles, or even way smaller and larger): #586 
> 
> This suite of grid-related features will live under the Grid checkbox's popover menu. Disabling the checkbox will turn off all rendering of grids. The popover dropdown next to the checkbox allows selectively enabling and disabling specific grid rendering features and changing certain settings like lines or dots for the grid style, the resolution of the grid (based on a chosen unit of measurement, either pixels or real-world units), and even setting the grid to work based on polar coordinates or logarithmic scales in the future.

For the MVP grid snapping, we want:

- [x] Hook up the grid button in the options bar of the document to enable and disable all grid features
- [x] Transforming a layer or point, such as dragging, grabbing (the <kbd>G</kbd> of G/R/S), nudging, etc., should snap (round) it to the nearest integer in document coordinates

**Comment by 0HyperCube** [comment]
![grid overlays](https://github.com/GraphiteEditor/Graphite/assets/78500760/04c730fb-fbb9-4145-8b62-37fb4015463f)
