### ISSUE TITLE
Might want to consider optimizing for speed instead of optimizing for code size

### ISSUE THREAD

**Issue by protheory8** [GraphiteEditor/Graphite#32]
Code size optimizations may slow down the code: https://github.com/rustwasm/wasm-pack-template/issues/27

**Comment by Keavon** [comment]
Let's optimize for development speed (i.e. minimal compilation/build time) until we get to the part where we are performance constrained. Release builds should probably prefer performance over file size within reason, but realize it's still being served by a CDN to random visitors who will have to load it all in their browser.

Please set the build options as you see fit according to these goals.

**Comment by protheory8** [comment]
Left `opt-level` on `s` for now.

**Comment by Keavon** [comment]
Is this resolved for now? Can we close it?

**Comment by protheory8** [comment]
We ended up with optimizing for code size instead of speed so not really, but we can close it anyway.

**Comment by Keavon** [comment]
Ok. Feel free to reopen this issue in the future if it becomes time to reevaluate that decision.
