### ISSUE TITLE
Eyedropper Tool color selection doesn't actually set the color

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#326]
The Eyedropper Tool picks a color and shows it in the primary working color swatch in the bottom left. But drawing a shape with this color uses the old color, and swapping the primary and secondary working colors resets them to the original pair from before the Eyedropper Tool was used. In other words, the Eyedropper Tool is doing nothing other than showing a fake color in the swatch.

**Comment by henryksloan** [comment]
This is a regression; I'll try to track it down tonight.

**Comment by Keavon** [comment]
#300
