### ISSUE TITLE
wasm-pack causes an npm install issue on m1 mac's

### ISSUE THREAD

**Issue by mfish33** [GraphiteEditor/Graphite#396]
wasm-pack is a necessary tool in order to build the web assembly that graphite is using however the npm package is just a shim to make sure it is installed on your system. This shim does not support the arm 64 package, however, installing directly using cargo works fine. Here is a link to the GitHub issue: https://github.com/rustwasm/wasm-pack/issues/952.  To solve this in the meantime it makes sense to move wasm-pack to an optional dependency so that it does not break the build for those on m1 compters.

**Comment by mfish33** [comment]
Closed since it was merged in #394

**Comment by Keavon** [comment]
Although we moved it to an optional dependency in Graphite, it still requires manual work to install wasm-pack directly. I'd suggest we keep this open until it's fixed directly in the wasm-pack project.

**Comment by Keavon** [comment]
wasm-bindgen 0.10.2 fixed this issue, but it's broken on Windows. So we're waiting on a fixed version before upgrading.
