### ISSUE TITLE
Fix overlaid scrollbars on Firefox

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#398]
Since Firefox doesn't support the non-standard WebKit overlaid scrollbars CSS properties, and its "standard" API that it does support is terrible, the scrollbars end up displacing the content which breaks the layout, especially on horizontally scrolling content. I tried integrating the Overlay Scrollbars and Simplebar JS libraries but they do some crazy things to the DOM which massively breaks our styling. We might need a custom solution, or to use JS, or find some other workaround.

**Comment by 0HyperCube** [comment]
@Keavon We have overlay scrollbars in firefox stable now (at least on my distro)

**Comment by bjorn3** [comment]
Firefox switched from gtk scrollbars to drawing the scrollbars itself. This was necessary to remove the X11 connection from content processes. Before that the browser sandbox was trivial to evade by remote controlling another process using said X11 connection.
