### ISSUE TITLE
Welcome screen for empty tabs

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#405]
Instead of opening a blank document, we should have a welcome screen (like VS Code's) which displays in place of the documents. It should show the Graphite logo, perhaps some relevant information about its alpha status and file format incompatibility, other informational messages, maybe links to tutorials or documentation in the future, and a big button to create a new document (with #523).

This should probably be, itself, a tab in the place of the document tabs. Since currently we can only display document tabs in the left column of the workspace, we may need to either hack something briefly or begin on #195. I think the best UX would be hardcoding the behavior where the welcome screen panel shows up in the place of where a document panel tab was closed if there are zero other places where document panels exist docked in the workspace (that way, the Properties and Layer Tree panel column doesn't take up the whole editor all of a sudden when closing document tabs).

**Comment by iamgabrielsoft** [comment]
Is there is definitive UI for the dialog screen?

**Comment by Keavon** [comment]
Not yet. Even if we just set it up where it's a Vue component that can easily have its HTML changed around, that'd be great. Then I can work on the finer details of the design at that point.

**Comment by iamgabrielsoft** [comment]
Till surprised I didn't get a mail when you replied. 

Okay sounds cool,  looking at using the discord logo for it
