### ISSUE TITLE
An opened file doesn't populate its layers, causing a crash when they're clicked in the viewport

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#430]
This is a regression since the *File > Open* system used to work. Now this is more urgent with the auto-save system enabled, causing this bug to be encountered by default (and potentially causing a broken state where the only fix is to clear the site's IndexedDB storage).

**Comment by 0HyperCube** [comment]
This is I think due to the layerdata not being saved (which it probably should be to save if a layer is hidden etc)

**Comment by Keavon** [comment]
> This is I think due to the layerdata not being saved (which it probably should be to save if a layer is hidden etc)

This used to work though. It's a regression.

**Comment by 0HyperCube** [comment]
I forgot layerdata is automatically generated if missing (although you may still want to save it), instead it appears the problem (introduced when folders where added) was that `handle_folder_changed` which called an `ExpandFolder` operation recreating the entries was removed. The fix should be to add back the new `FolderChanged` operation on the root when a new document is loaded.
