### ISSUE TITLE
Path Tool: allow dragging handles, not just anchors

### ISSUE THREAD

**Issue by leonardpauli** [GraphiteEditor/Graphite#471]
Create + use new fn `closest_handle` instead? (or better, restructure code with path control-point refs such that multiple disconnected iterations/brute force checks won't be necessary).

Seems like it checks bezier curve endpoints (anchor points) but not its other control points (direction handles)?  Note how, on an ellipse, pressing down on a handle marks it correctly, but then when dragging, it drags the closest anchor instead.

_Originally posted by @leonardpauli in https://github.com/GraphiteEditor/Graphite/pull/451#r780704320_

**Comment by otdavies** [comment]
This was a known bug upon merging in, Keavon felt it was a helpful additional even in its current state. Lets jump in and fix it together :D
