### ISSUE TITLE
Redesign node icons

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#483]
We need to come up with a design language for node icons. Then we can replace these ones for folders and vector shapes (among other future ones, that aren't needed yet in the app but are needed in the design mockups).

![Folder icon](https://files.keavon.com/-/SaddlebrownRubberyNeontetra/capture.png) ![Path icon](https://files.keavon.com/-/PointedExoticShihtzu/capture.png)

**Comment by 0HyperCube** [comment]
@Keavon Also for text layer (will work on that next)

**Comment by Keavon** [comment]
Excellent, that's exciting to hear! Let's touch base on that before you resume.
