### ISSUE TITLE
Change the mouse cursor to 'grabbing' when holding MMB and moving mouse on the canvas

### ISSUE THREAD

**Issue by asyncth** [GraphiteEditor/Graphite#486]
Currently this only happens when the Navigate tool is active.
Originally was a part of #463.

**Comment by Keavon** [comment]
Also: holding <kbd>Space</kbd> with <kbd>LMB</kbd>-drag is pan for users without a middle mouse button.

Additionally, <kbd>Shift</kbd><kbd>MMB</kbd> drag up/down should zoom and display the magnifying class cursor just like <kbd>LMB</kbd> dragging to zoom with the Navigate Tool active. And <kbd>Ctrl</kbd><kbd>MMB</kbd> drag around to rotate the canvas should display the cursor we'll use for document rotation. (Can be tested with a placeholder for now then set back to `default`.)
