### ISSUE TITLE
New Document dialog

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#523]
We need the *File* > *New* menu (and <kbd>Ctrl</kbd><kbd>N</kbd> shortcut) to open a dialog menu where the document name and artboard dimensions (or infinite canvas) can be chosen.

**Comment by 0HyperCube** [comment]
Should this use the rust widget api?

**Comment by Keavon** [comment]
Ideally, yes. But that means we need to build a system which can ideally be triggered entirely by the backend to request a dialog be shown with the given layout defined in Rust. And then port over the existing dialogs to use that system. But that's something we've been needing to do for a while now because the current JS-based dialog definition system is pretty unstandardized and un-ideal.

**Comment by iamgabrielsoft** [comment]
Has this being done?
