### ISSUE TITLE
Setting pivot of rotation/scale in the transform cage

### ISSUE THREAD

**Issue by psvoboda76** [GraphiteEditor/Graphite#525]
It would be useful to provide a center of rotation. 

This can be especially useful for creating gauges etc. The center of rotation should be remembered (eg. saved with object).

Is this functionality planned, or is it implemented and did I miss it?

**Comment by Keavon** [comment]
This requires a bit more design thought to figure out how this relates to the Select Tool's transform cage and how it relates to the layer transform and the future transform node. It will have to be left out for the moment, unless we want it to be built as a stopgap feature, for the moment but I'll file this under an upcoming sprint. It could be a good feature for a new contributor as a stopgap (pre-node graph). It's a relatively important feature but won't make it in time for the alpha release this week.
