### ISSUE TITLE
Add a shortcut to pick a random color

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#549]
This would be useful for testing and probably useful for actual art some of the time as well. Perhaps it could be added to, I'll just arbitrarily say, <kbd>Alt</kbd><kbd>C</kbd>. It would replace the primary color swatch with a randomly picked hue, saturation, and value.

**Comment by FlorentCollin** [comment]
Hi, I would like to work on this issue as it is labeled as "Good First Issue". I already have a working implementation, but I had to add a dependency to the "rand" crate in order to generate random numbers. I couldn't find any code in the repository that generates a random number. Is there any already? 

Also, the rand crate might be a bit heavy just for generating a bunch of random numbers that doesn't need to be cryptographically secure.

**Comment by Keavon** [comment]
@FlorentCollin Check where we are generating UUIDs in many locations throughout the editor code. You should be able to use that as a random source.

**Comment by FlorentCollin** [comment]
I found the part where you generate UUID

**Comment by FlorentCollin** [comment]
I found the code to generate a UUID, should a function be creating to only generate an u8 random number or a simple usage like this ok?

https://github.com/FlorentCollin/Graphite/blob/1f8580d4f73fa3fdbb86db4e964b8e6e0fe3162b/editor/src/viewport_tools/tool_message_handler.rs#L108-L111

Also, is a button necessary in the graphical interface?  If yes, can you give me some guidance on where to place it (maybe below or next to the Swap and Reset button in the bottom left corner) ?

**Comment by Keavon** [comment]
No button in the UI is necessary since this is kind of a "hidden" feature. A good name for the message would probably be `SetRandomPrimaryColor`. You should only need to call to generate the UUID once, then you can partition the provided u64 into four u8 values with bitwise operations.

**Comment by FlorentCollin** [comment]
That makes sense, I'm gonna modify the code and send a pull request. Is there anywhere in the documentation where this shortcut should be mentioned?

**Comment by Keavon** [comment]
Just comment the code you touch/add with `/// Doc comments` and that'll be fine. I can mention it on Discord to the other developers to use in testing. Someday we'll have a nicer means of discoverability, like a searchable action palette.

**Comment by Keavon** [comment]
Hey @FlorentCollin, just checking up how this is going. Need any help?
