### ISSUE TITLE
Layer system for SVG elements in the document

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#55]
We need to eventually draw a layer panel with a layer stack (with folders, so it's a tree structure). Each layer is used to keep track of a Kurbo shape in memory, and to allow the user to select the shapes and modify them (instead of just adding new shapes like we do right now). Then we will need each modified Kurbo shape to request a rerender (into SVG element syntax) and an update to the attributes of the existing SVG element (or addition or removal of elements in the SVG tag when a shape is added or deleted).

**Comment by TrueDoctor** [comment]
I might start working on that today please comment below/@ me on Discord to ask if I have already started working or am still procrastinating
