### ISSUE TITLE
Improve the snapping system

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#550]
The current approach is very MVP.

**Comment by Keavon** [comment]
> Keavon — 02/13/2022
> @0hypercube how difficult would it be to display the point that is being snapped to?
> i.e. if you have something (like a gradient or another anchor point) snapping to an anchor point, rendering the anchor point's square to show what is causing there to be a line across the screen

> 0hypercube — 02/13/2022
> Only for shape points?

> Keavon — 02/13/2022
> Are there things other than shape points which are the source of snapping candidates?

> 0hypercube — 02/13/2022
> layer bounds and centres

> Keavon — 02/13/2022
> Ideally in that case, we'd draw the entire shape's outline
> So the specific anchor point when snapping to an anchor point, and the entire shape outline when snapping to the bounding box edge/center.

> 0hypercube — 02/13/2022
> Probably reasonably easy, but I'm quite busy for the next few days

> Keavon — 02/13/2022
> Ok, good to hear it's easy. No worries about getting it done immediately, but I was wondering how much work it would be. I'll put it near on the priority list if you're interested in taking that on next time you have some free time and an interest.
> More more little improvement would be making the anchor points snap to other anchor points
> https://files.keavon.com/-/LimeComfortableLimpkin/capture_2_.mp4
> I'll file issues for both of those 

> 0hypercube — 02/13/2022
> All snapping should snap to all path control points in the document?

> Keavon — 02/13/2022
> I think generally: points to points, bounds to bounds
> So dragging around an anchor point should snap to the other anchor points (plus also bounds)
> But drawing a new rectangle, or resizing the cage for an existing shape, should only snap to other bounding boxes

> 0hypercube — 02/13/2022
> Should snapping bounds to bounds display a shape outline?

> Keavon — 02/13/2022
> Yes

**Comment by 0HyperCube** [comment]
@Keavon Do we also want to show the points on the faint lines?

**Comment by Keavon** [comment]
@0HyperCube what points?

**Comment by 0HyperCube** [comment]
The points being snapped to (orange circles in the above video)

**Comment by Keavon** [comment]
Yeah, that would be great to visualize those. I assume in that case we're seeing either the bottom-center as well as the bottom corners of the bounding box? Or maybe the bezier handles? I think in Graphite we only really need to see one of those points (preferably the bottom center one).

But the more important improvement with the snapping system would be to reduce the spam and self-collision detection. I can describe that in a bit more detail for you on Discord if you'd like.

**Comment by 0HyperCube** [comment]
What we want to snap (discussed in discord, posted here for future reference):
![image](https://user-images.githubusercontent.com/78500760/165348391-e43e5894-9569-4d35-956a-7248a6048bed.png)

We also do want indicators on each line for what you are snapping to.
