### ISSUE TITLE
Undoing while drawing with pen causes app to panic and freeze

### ISSUE THREAD

**Issue by nyanpasu64** [GraphiteEditor/Graphite#558]
- Visit https://editor.graphite.rs/.
- Click Pen.
- Click the canvas to begin drawing a line.
- While the line is following the mouse, press Ctrl+Z.

The page freezes. F12 shows:

```
error	panicked at 'called `Result::unwrap()` on an `Err` value: LayerNotFound([14734871127979280017])', editor/src/viewport_tools/vector_editor/vector_shape.rs:151:119
error	panicked at 'already borrowed: BorrowMutError', frontend/wasm/src/lib.rs:38:19
```

Browser: Firefox 97.0 (64-bit)

**Comment by TrueDoctor** [comment]
Was fixed in ff5dff948b3a708fc9a85c8607c820664a339ca4
