### ISSUE TITLE
Undoing during freehand line results in editing previous undo state

### ISSUE THREAD

**Issue by nyanpasu64** [GraphiteEditor/Graphite#559]
- Visit https://editor.graphite.rs/.
- Click "Freehand Tool".
- Draw a line on the canvas. (If you skip this, you edit the initial state of the document, and can't undo your subsequent line.)
- Draw a line, and while the mouse is held, press Ctrl+Z.

The second line vanishes.

- Move the mouse again.

The second line reappears. In F12, I get: `error	DocumentError: LayerNotFound([8883258809406379036])`. Releasing the mouse and pressing Ctrl+Z undoes both lines at once.

If you draw multiple lines upfront, you can press Ctrl+Z multiple times and edit multiple undo steps.

Possibly related to #558.

Browser: Firefox 97.0 (64-bit)

**Comment by nyanpasu64** [comment]
OK, every tool has its own misbehavior if you undo during a draw operation. The Line/Rectangle/Ellipse/Shape tools spam `DocumentError: LayerNotFound([])`. The spline tool acts like freehand.

**Comment by Keavon** [comment]
Closed by #560

**Comment by nyanpasu64** [comment]
Apparently this got reopened and closed a second time. Was that intentional?

Testing at https://editor.graphite.rs/, undoing during a freehand stroke moves back by 1 undo step, but fails to remove the object being created, and prints `error	DocumentError: LayerNotFound([15614631032649384611])` as well. Continuing to drag the mouse no longer has an effect (unlike before). Now when you undo a second time, you revert two lines at once. If you redo instead of undoing, you redo a no-op edit.

**Comment by TrueDoctor** [comment]
Yes, that is true my main priority was to keep the editor from crashing the `error` is basically an indicator that the tool assumes there to be a layer that no longer exists. The inconsistent behaviour has to be dealt with as well, might have closed the wrong issue then, sorry about that
