### ISSUE TITLE
Allow line weights to be floats

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#587]
We currently are using `u32` line weights because `f32` and `f64` don't implement `std::hash::Hash` which is needed for the options bar UI widgets.

Hint: a starting point for going at this issue is searching the project for `"Weight"` (in quotes), changing `is_integer: false` to `true`, and then trying to go replace all the `u32` instances with `f32` and `f64`. We probably want to stick with `u64` for the UI widgets and then maybe use `f32` for line weights or maybe switch that all over to `f64` also. The hard part is finding a solution to the `Hash` trait, since oddly floats in Rust don't implement it.

**Comment by 0HyperCube** [comment]
@Keavon We don't actually need the hash trait any more. Just remove it from the `__OptionsUpdate` enum.
