### ISSUE TITLE
Improve usage of history states throughout the application

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#595]
History states (undo/redo) are implemented, but many tools and actions and messages don't save history states when they need to. The resulting experience is quite unpleasant since it's easy to lose work or end up undoing/redoing way more than expected. This task involves experimenting with lots of everything, basically doing a QA test on everything, and fixing all the problems with history wherever one shows up. Related: #559

**Comment by RahulHi** [comment]
I'll work on this one.

**Comment by Keavon** [comment]
How is this going @RahulHi? Need any help?

**Comment by Keavon** [comment]
Hi @RahulHi, just another friendly check-in. Let me know if there's anything I can do to help push this along. Cheers!

**Comment by RahulHi** [comment]
@Keavon Will do! There isn't anything right now, but I will be sure to let you know of any questions I have!

**Comment by noblehelm** [comment]
Should every action produce a history to enable undo/redo? Even actions like using the Navigate Tool?

**Comment by Keavon** [comment]
@noblehelm Technically, using the Navigate Tool modifies the document, but we ideally would like to filter out some obvious things like that from counting for history. But it's probably better if we can make that opt-out rather than opt-in since currently it's too easy to implement features and forget about making them support history. The history system is quite crippled right now and really any improvements would be of vital importance.

**Comment by Keavon** [comment]
Closed by #932
