### ISSUE TITLE
Properties panel doesn't go blank after clicking in Layer Tree panel to deselect, requires a second click to blank it

### ISSUE THREAD

**Issue by bjorn3** [GraphiteEditor/Graphite#597]
The first click in the empty area of the Layer Tree deselects the layers but the Properties panel doesn't go blank. It takes a second click in the same place to make it go blank.

https://user-images.githubusercontent.com/17426603/164511902-de672dbd-bcdf-4a4f-b0cb-3353569c54b6.mp4

**Comment by Keavon** [comment]
Clicking blank space in the Layer Tree panel should deselect the selection. However it's a bug that it requires clicking *again* to make the Properties panel go blank.

**Comment by 0HyperCube** [comment]
It appears that you can draw things (i.e. using the rectangle tool) by dragging the empty space in one of the panels.

**Comment by Keavon** [comment]
> It appears that you can draw things (i.e. using the rectangle tool) by dragging the empty space in one of the panels.

Oh you're right, that's really weird.

**Comment by bjorn3** [comment]
It doesn't just happen in the layer tree panel. It also happened in the property pane for me a couple of times. Can't really reproduce though.

**Comment by Keavon** [comment]
It looks like dragging the gutter between panels to resize them also causes a deselection. And when you click and drag (but not just click) in blank space in the properties panel. This might be due to the tools interacting with the out-of-the-viewport areas and it's just acting like it is doing a blank selection with the Select Tool.

**Comment by Keavon** [comment]
Indeed, even dragging in the footer or title bar also causes it to operate the tool. So presumably that's the real bug. (Besides possibly the second bug that may or may not be related where deselecting in the Layer Tree takes two clicks to blank the Properties panel.)

**Comment by 0HyperCube** [comment]
Indeed (with rectangle tool)
![gutter](https://user-images.githubusercontent.com/78500760/164514665-f0127846-f76a-4180-baed-b99ad871521c.gif)

**Comment by Keavon** [comment]
@0hypercube the bug where you can click and drag to use tools outside the viewport was introduced in #589. My best guess is this may be from the changes to the input preprocessor which dealt with multiple button clicks on mousemove.

**Comment by 0HyperCube** [comment]
The clicking to deselect layers was intentional, other behaviour has been resolved by #600.

**Comment by 0HyperCube** [comment]
Sorry the double click to clear the layer panel has not been resolved.
