### ISSUE TITLE
Overflow on polygon with 256 sides

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#612]
Setting the sides to 256 in the shape tool and then drawing causes an overflow panic (assuming you are running with debug asserts). This can be fixed by either casing to a larger integer (i.e. u32) or by subtracting 1 rather than adding one (giving the same result)

**Comment by Keavon** [comment]
We're using a u8? Why not a u32 or u64 like most normal numbers?

**Comment by Keavon** [comment]
I can't reproduce this crash.

**Comment by 0HyperCube** [comment]
@Keavon It needs to be compiled with debug assertions (otherwise int overflow is ignored)

**Comment by linda-zheng** [comment]
@Androxium and I are interested in working on this!

**Comment by Androxium** [comment]
Interested in working on this with @linda-zheng !
