### ISSUE TITLE
Remove overlay ownership from VectorShape / VectorPoint

### ISSUE THREAD

**Issue by otdavies** [GraphiteEditor/Graphite#616]
Currently overlays are tightly coupled to _VectorShape_ / _VectorPoint_, we want to change this relationship.

**New approach:** 
Send the _VectorShapes_ to an _OverlayRenderer_ and use an immediate mode renderer to render it.

This is part of moving toward this approach (WIP):
![ShapeEditing (1)](https://user-images.githubusercontent.com/3145170/164816430-425ed22c-6e95-4eb1-aa81-e1b50119851c.png)

**Comment by Keavon** [comment]
Closed in favor of #605.
