### ISSUE TITLE
Cannot paste into properties or editing text field

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#618]
If you try and use <kbd>Ctrl</kbd> + <kbd>V</kbd> in an input in the properties panel or an editing text field in the document then nothing happens. This can be frustrating to users who want to copy and paste colour hexes or text into either the field in the document or in the properties panel. This is likely due to a hook on keyboard events calling `.preventDefault()`.

**Comment by nupsi** [comment]
The `.preventDefault()` is called in the `onPaste` method in [input.ts](https://github.com/GraphiteEditor/Graphite/blob/e8fdfd69f9798f2b3d991fa4e72149493c478ac9/frontend/src/lifetime/input.ts#L232=) on line 232.

- Maybe the event target `e.target` could be used to allow/prevent the default action?
- Does the editor instance require the pasted items when pasting to a field?
  - If the pasted value contains svg data, the value will be pasted as an svg and as a text to the active input.
- Should the `onPaste` method be ignored when targeting an input?

```ts
const onPaste = (e: ClipboardEvent): void => {
	const dataTransfer = e.clipboardData;
	if (!dataTransfer) return;
	if (e.target instanceof HTMLElement &&
		(e.target.nodeName === "INPUT" || e.target.nodeName === "TEXTAREA" || e.target.isContentEditable)
	) {
		return;
	}
	// ...
```

Something similar can be seen in the [`shouldRedirectKeyboardEventToBackend`](https://github.com/GraphiteEditor/Graphite/blob/e8fdfd69f9798f2b3d991fa4e72149493c478ac9/frontend/src/lifetime/input.ts#L44-L52=) method on lines 44-52 in the same file.

Not going to PR the issue, but hope this helps!
