### ISSUE TITLE
Snapping system is not precise

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#630]
From [here](https://github.com/GraphiteEditor/Graphite/pull/621#issuecomment-1119205774):
> It's hard to tell, but I think the handle points, when being dragged and snapped to things, are snapping a few pixels vertically offset from true. Try dragging a handle point and snapping it to the bottom of a neighboring shape and notice how it's below the bottom. This might also be the case for anchor points, but instead of vertically it's some other sort of offset. Try out the snapping of anchor and control points to other shapes then zoom in to see if they are precisely located in the same exact location (down to many decimal places before floating point error comes into play).

Reply by @0HyperCube about this:

> Yes, if you drag a point with the path tool, it will snap your mouse position and then add the offset dictated by how far your mouse was originally away from the centre of the point. Also would cause more merge conflicts for the path refactor.

~~So I'm marking this as blocked on #605.~~

**Comment by 0HyperCube** [comment]
This has been fixed as the path tool now puts the centre of the square at the mouse position.

**Comment by Keavon** [comment]
@0HyperCube do you know which PR or commit fixed this, for the record?
