### ISSUE TITLE
Set up downloadable builds through Tauri

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#636]
[Tauri](https://tauri.studio/) is an Electron alternative that uses the local OS's webview to provide a low-overhead web wrapper as a desktop app. It's part of the Rust ecosystem.
This is actually something we can tackle sooner than I was previously expecting.

- [ ] We should probably wait to switch to Svelte (#635), but this isn't a strict blocker
- [x] We should probably wait for Tauri's official 1.0 release ~~(as of writing, it's at the release candidate stage)~~ ([Released](https://tauri.app/blog/2022/06/19/tauri-1-0))
- [ ] We will want to configure our build infrastructure to provide [binaries](https://tauri.studio/guides/distribution/publishing) and [automatic updates](https://tauri.studio/guides/distribution/updater) as part of the deployment process
- [ ] And we'll want to add some in-app functionality to nicely prompt to install updates

Longer-term:
- We'll want to run the Rust code natively instead of inside the webview's WASM runtime, especially once we're doing our own rendering rather than using the browser's SVG engine (since the perf bottleneck is currently on that render engine, not ours)
- Tauri will be useful for hosting the [Monaco code editor](https://microsoft.github.io/monaco-editor/) for node source code editing

**Comment by felipetesc** [comment]
https://github.com/GraphiteEditor/Graphite/pull/873#issuecomment-1337022165

> @felipetesc Did you have similar issues with `instantiateStreaming` receiving the wrong mime type in `cargo tauri build`? The aim of this pr is a bit different because we acutally aim to execute the logic locally in order not to be limited by wasm constraints. Would you mind taking a look at this pr and potentially help with some of the issues? I'm a total newbie to tauri hence any feedback would be much appreciated.

_Did you have similar issues with instantiateStreaming_ ?
No. I didn't find any issues with `cargo tauri build`. However, I don't know how you proceeded, that is, what you have done before executing the previous command. 
What I did can be found at https://github.com/felipetesc/graphite-desktop/blob/master/README.md

"We actually aim to execute the logic locally"...
Question:  Would be possible to use a single Javascript file to ask for any resources from the web server (I read at https://github.com/GraphiteEditor/Graphite/tree/master/frontend that you are using webpack and I don't know if that's the case already, sorry for this) ? 
The reason for this request is to allow us to use the file [main.js 
](https://github.com/felipetesc/graphite-desktop/blob/master/src/main.js) to make all operating system calls from the same point. If any other file needs a resource it is going to use this js. And if we want to create  a server with Rust, or Python, Go (wherever), we will exclusively deal with the complications of one JS. In a sense, it's like building a an app for pwa. 
I'm most probably wrong about several assumptions I've made here.

**Comment by felipetesc** [comment]
> * We'll want to run the Rust code natively instead of inside the webview's WASM runtime, especially once we're doing our own rendering rather than using the browser's SVG engine (since the perf bottleneck is currently on that render engine, not ours)

Question:
Is this similar to what you want https://github.com/RazrFalcon/resvg ?  On top of glow, or wgpu, or ... ?
