### ISSUE TITLE
Implement the File > Import menu

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#671]
Currently we can drag image files into the editor. But we should be able to do that with File > Import as well.

---

In `menu_bar_message_handler.rs`, reference the `"Open…"` menu entry and how it calls `PortfolioMessage::OpenDocument`. Make another PortfolioMessage variant called `PortfolioMessage::Import`. Define its handler in `portfolio_message_handler.rs`, which should call `FrontendMessage::TriggerImport`.

In `editor/src/frontend/frontend_message.rs`, add something next to `TriggerFileUpload` called `TriggerImport`. Then also rename `TriggerFileUpload` to `TriggerDocumentOpen` (use global search to rename it throughout the project in the JS and Rust codebases). Use the global search to also guide you where else to add your new `TriggerImport` message, including a keyboard shortcut entry in `input_mapper.rs`, a JsMessage in `messages.ts`, and a subscription for it in `portfolio.ts`.

In `portfolio.ts`, instead of calling `editor.instance.open_document_file()`, you'll want to use `editor.instance.paste_image()`. But you need to make sure the user is importing an image, and you'll want to provide the correct MIME type and `u8` byte array for the image. You can reference `Document.vue:274` (`pasteFile()`) and `input.ts:317` for examples of where this image preparation occurs. If the file isn't an image, either nothing should happen or an error dialog should say that only images are supported (see `input.ts:348`).

In the end, it should be possible to upload JPG, PNG, and SVG images with the *File* > *Import…* menu entry and the <kbd>Ctrl</kbd><kbd>I</kbd> shortcut.

**Comment by brunosxs** [comment]
I'll try to tackle this one...

**Comment by Keavon** [comment]
@brunosxs Sorry, you're a day late :) I completed this issue yesterday. If you'd like any help picking out a different issue, I'd be more than happy to lend some suggestions.

**Comment by brunosxs** [comment]
Ops, my bad... I left the tab open a day or so ago, not sure if it had paid attention to the task.
I just want to familiarize myself with the source. I'll try to grab any low pri issues

**Comment by Keavon** [comment]
Sure thing! And if you're curious to see the diff which implemented this feature, [here it is](https://github.com/GraphiteEditor/Graphite/commit/f3bdf970f4d432b73d5cf8579a414680626c2a96). The left column of https://github.com/GraphiteEditor/Graphite/projects/1, especially the ones labeled `P-Low` and `P-Medium`, should probably fit your needs. I might suggest one of these three to get started with:
- #737
- #704
- #542
