### ISSUE TITLE
Question: Collaboration

### ISSUE THREAD

**Issue by daxpedda** [GraphiteEditor/Graphite#69]
Are there any plans to introduce live collaboration between multiple clients?

I was just listening to the presentation in game dev and considering that there is an API "endpoint", I thought it might be possible to have multiple end clients connect to a Graphite Server to collaborate on the same document together.

I very much realize that this is quiet a crazy idea :smile:

**Comment by Keavon** [comment]
"Multiplayer" editing (like Google Docs) is a planned feature for both the web and desktop client. It is an important design requirement to keep in mind while we make technical decisions but we can't prioritize it until a bit later on because core editor features are certainly the most crucial.
