### ISSUE TITLE
Modifying the transform of a zero-area layer causes a crash

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#699]
There are multiple symptoms:

- Dragging a transform cage breaks when a layer's bounding box has 0 area (width or height is 0), achieved by scaling with, e.g., <kbd>S</kbd> <kbd>Y</kbd> <kbd>0</kbd>. It makes the shape disappear, and then trying to draw other shapes makes the editor crash.
- In the Properties panel, after setting a layer's X or Y scale or dimensions to 0, setting it back to a non-zero value crashes the editor. Even rotating it causes the crash. Also the rotation sometimes shows "NaN"`.

The expected result is that scaling along the axis which was previously squashed to 0 should instead just do nothing, meaning that the user drags along that axis and it simply doesn't end up changing. Typing a new value in the Properties panel should just display 0 again for the Dimensions, and either 0 for the scale or whatever value the user types which ends up doing nothing. Rotating should work, though, and then scaling along an axis would mean that the infinitely-thin sliver of a layer becomes a rotated, sheared sliver.

**Comment by Bobox214** [comment]
I am currently looking at that, the panics related to 0-scale shapes.
I will provide a PR for, hopefully, all of the described symptoms, (which I have been able to reproduce) and a bit more.

**Comment by Keavon** [comment]
> I am currently looking at that, the panics related to 0-scale shapes. I will provide a PR for, hopefully, all of the described symptoms, (which I have been able to reproduce) and a bit more.

Glad to have your help! I've assigned the issue to you. Once you have a PR open, I will also set it to In-Progress. Thanks for helping aim to resolve this crash!
