### ISSUE TITLE
Alter behavior of dragging unselected layers through selected layers

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#705]
Right now, when an unselected layer occludes a selected layer, the user is able to click and drag on the selected layer *through* the unselected layer and make it drag. The behavior should be altered so that it requires direct click targeting to be dragged, otherwise a new drag occurs on the unselected layer, thereby selecting it immediately and beginning to drag it.

**Comment by dchiasson** [comment]
Just to clarify, the desired behavior is that when an unselected occluding layer is clicked or dragged (without the shift modifier), all other layers are deselected and the occluding layer will selected or dragged, right?

**Comment by dchiasson** [comment]
Ok, I think this behavior is correct, I just need a few tips on the correct idioms.
