### ISSUE TITLE
Improve Path tool layer and anchor point selection behavior

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#722]
- [x] Deselects the shape layer (from the layer panel) when clicking into empty space
- [x] Selects all the shape's layer (in the layer panel) and selects all the anchor points when clicking in the filled area of the shape
- [x] Selects the targeted shape when dragging (regardless of whether or not it was previously a selected layer or whether it had any or some or all anchor points selected) and then drags the whole shape similar to the Select tool
- [x] Selecting an individual already-selected anchor point deselects all but the clicked one

**Comment by noblehelm** [comment]
Can I try to work on this?

**Comment by Keavon** [comment]
@noblehelm Thanks for mentioning that some of this is already implemented! I went and checked off the ones that are implemented, and clarified a few of them. Those remaining are still needed, so you're welcome to work on this and I can help clarify anything if you need help with it. I saw you also commented on the history system, I'll just say that is of greater importance to usability but it's up to you which you'd like to work on.

**Comment by noblehelm** [comment]
For the 4th task, is there a way to differentiate from a simple click and a _click and hold_? Because I think that would probably get in the way of selecting multiple anchors with Shift and releasing Shift to drag them.

**Comment by noblehelm** [comment]
One caveat is that the InputEventHandler treats KeyUp(Lmb) as DragStop always for the Path tool, according to the images below:
![image](https://user-images.githubusercontent.com/5214283/195427365-140f1d55-94d3-4b06-a363-dec3ed885cf6.png)
![image](https://user-images.githubusercontent.com/5214283/195427424-6b8ea4a3-0d14-4876-a80e-7be3f06eb479.png)

So, should I separate into two different INputEvents, one for the already present DragStop, and another for a SimpleClick? If so, how can I separate it? Should I treat a mouse cursor movement as <= 10px in between MouseDown and MouseUp as a single click, and anything else as DragStart/DragStop?

**Comment by ChrisMend19** [comment]
Test comment for assignment for this issue

**Comment by OllieDolan** [comment]
Working on issue
