### ISSUE TITLE
Extend welcome screen button click area to labels

### ISSUE THREAD

**Issue by brunosxs** [GraphiteEditor/Graphite#738]
This requires adding icon support to the `TextButton` widget Vue component so it fits the UI spec:

![image](https://user-images.githubusercontent.com/4388688/181457448-44c844ab-68a4-40d3-8e61-95a5979fa506.png)

Then possibly applying special CSS in `Panel.vue` to remove the gray background so it appears more like it does right now.

---

**Original Issue:**

Just started using graphite and came into the realization that it should be clear what is clickable. I thought that this was a button:
![image](https://user-images.githubusercontent.com/1557903/180667517-40d8e070-4ac6-4918-89e8-49042beef2e0.png)

Instead, just the icon is clickable.
Seeing the colon later made me realize it was just explaning the shortcut, it is still bad because the icon and the label feel like a separate entity from the shortcut label. Also, the icon is very small, not really optimal for touchscreens which Graphite is also targetting.
I don't know if the project has ui guidelines as of now (I found a miro board on the user-interface channel in discord but had no access), do we?

**Comment by Keavon** [comment]
Thanks for your feedback on that! I wanted to make those part of the button but it would add some complexity and I decided against doing that initially, but with your suggestion, that's definitely worth changing sooner than later. One more thing to mention is that we will need to feed this layout from the Rust backend so it can provide the keyboard shortcut correctly based on the user's OS (#206).

Increasing the icon size, although it might help with touchscreens, would deviate from the UI spec. For touchscreens, we'll probably want to just increase the entire UI size, which will be a setting in the future configuration panel.

The UI spec is, currently, just an Adobe XD file I have on my computer. Any Miro board you may have found is old and never had anything on it. I have plans to port that content into some more formal UI documentation that will be part of the design section of the upcoming docs portal. Then we'll eventually port it over to a Graphite file once the app is up to the task of doing UI mockups.
