### ISSUE TITLE
Rotating object via property panel eliminates shear

### ISSUE THREAD

**Issue by dchiasson** [GraphiteEditor/Graphite#770]
![shear](https://user-images.githubusercontent.com/1863441/187081005-ad77e512-fa5b-49ca-a950-b26879c724e5.gif)

**Comment by Keavon** [comment]
I think the best way to prioritize this is to wait until we have the node-based transform system using the Transform node. Probably isn't worth the expendable effort of a temporary fix when that won't matter after we have nodes.

**Comment by Keavon** [comment]
Upon further thought, maybe this can be fixed without that much effort and it would probably be a quality of life improvement for users who run into this. Do you have any thoughts about this and its prioritization @0HyperCube?

**Comment by 0HyperCube** [comment]
> Upon further thought, maybe this can be fixed without that much effort and it would probably be a quality of life improvement for users who run into this. Do you have any thoughts about this and its prioritization @0HyperCube?

This would probably be somewhat ugly because of how skew combines with rotation and scale in the affine2.
