### ISSUE TITLE
Importing image just doesn’t work?

### ISSUE THREAD

**Issue by GoldsteinE** [GraphiteEditor/Graphite#780]
I try to import the attached image (I've tried both png and jpg versions of it, in both Chrome and Firefox, both via Ctrl+V and File → Import).

I get screen looking like this:
![image](https://user-images.githubusercontent.com/12019211/191933036-f8fccf39-c28b-4f45-ad64-4efeeece6dd0.png)

Trying to scale up the image in Properties reveals that the imported image is completely white.

[attached.png](https://user-images.githubusercontent.com/12019211/191932890-f4b43cfc-9f9e-40d3-95da-4066449d0e0a.png)
[attached.jpg](https://user-images.githubusercontent.com/12019211/191932901-87ec5f6a-76cd-4632-9a39-cf62a7eed630.jpg)

**Comment by Keavon** [comment]
Looks like this is a regression, I can reproduce it. The size shouldn't be 1x1 and the image shouldn't just be white. @0HyperCube are you able to take a look at this please?

**Comment by 0HyperCube** [comment]
I can reproduce this and so did @AnimateShadows. This is because someone changed the rust to use the snake case `image_data` and the vue to try and read the camel case `imageData` inside `FrontendImageData`.

**Comment by 0HyperCube** [comment]
Putting a serde rename on the image data fixes the issue
```rs
#[serde(rename = "imageData")]
pub image_data: Vec<u8>,
```

**Comment by Keavon** [comment]
Oh, that would be a change I made when I refactored the consistent usage of snake/camel case between the Rust and JS. Hopefully I didn't make any other mistakes during that process. Thank you for finding that!
