### ISSUE TITLE
[Crash Report] Vertical / Horizontal lines cause a crash when dragged

### ISSUE THREAD

**Issue by otdavies** [GraphiteEditor/Graphite#782]
**Steps To Reproduce**
1. Open the Graphite Editor at https://editor.graphite.rs.
2. Switch to line tool.
3. Draw a vertical line, snapped to vertical by using shift.
4. Switch to select tool.
5. Try to drag the line.
6. Crash.

**Browser and OS**
Chrome, Windows 10

**Stack Trace**
panicked at 'tried to transform point to non finite position', graphene/src/layers/vector/manipulator_point.rs:53:9

Error
    at https://editor.graphite.rs/js/app.6a8dfb0c.js:9:995
    at Object.n [as handleJsMessage] (https://editor.graphite.rs/js/app.6a8dfb0c.js:1:8158)
    at https://editor.graphite.rs/js/app.6a8dfb0c.js:1:8656
    at https://editor.graphite.rs/js/123.8b98810b.js:1:13830
    at N (https://editor.graphite.rs/js/123.8b98810b.js:1:5550)
    at Cn (https://editor.graphite.rs/js/123.8b98810b.js:1:13796)
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[2325]:0x1c8578
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[913]:0x174630
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[700]:0x1588a5
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1889]:0x1bbdd3
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1766]:0x1b6787
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1976]:0x1bf240
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[2532]:0x1cc402
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[2540]:0x1cc5d9
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1302]:0x1999c4
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[748]:0x15f80d
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1940]:0x1bdd14
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[95]:0x75758
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[442]:0x1273d7
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[54]:0x19197
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[58]:0x28114
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[131]:0x9d3b6
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[772]:0x162de6
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[899]:0x172bd7
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1446]:0x1a4127
    at Proxy.onMouseMove (https://editor.graphite.rs/js/123.8b98810b.js:1:8258)
    at Proxy.<anonymous> (https://editor.graphite.rs/js/app.6a8dfb0c.js:1:532)
    at m (https://editor.graphite.rs/js/app.6a8dfb0c.js:1:25571)
    at action (https://editor.graphite.rs/js/app.6a8dfb0c.js:1:23818)

```
panicked at 'tried to transform point to non finite position', graphene/src/layers/vector/manipulator_point.rs:53:9

Error
    at https://editor.graphite.rs/js/app.6a8dfb0c.js:9:995
    at Object.n [as handleJsMessage] (https://editor.graphite.rs/js/app.6a8dfb0c.js:1:8158)
    at https://editor.graphite.rs/js/app.6a8dfb0c.js:1:8656
    at https://editor.graphite.rs/js/123.8b98810b.js:1:13830
    at N (https://editor.graphite.rs/js/123.8b98810b.js:1:5550)
    at Cn (https://editor.graphite.rs/js/123.8b98810b.js:1:13796)
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[2325]:0x1c8578
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[913]:0x174630
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[700]:0x1588a5
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1889]:0x1bbdd3
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1766]:0x1b6787
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1976]:0x1bf240
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[2532]:0x1cc402
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[2540]:0x1cc5d9
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1302]:0x1999c4
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[748]:0x15f80d
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1940]:0x1bdd14
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[95]:0x75758
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[442]:0x1273d7
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[54]:0x19197
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[58]:0x28114
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[131]:0x9d3b6
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[772]:0x162de6
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[899]:0x172bd7
    at https://editor.graphite.rs/bf67697c3f7dd460.module.wasm:wasm-function[1446]:0x1a4127
    at Proxy.onMouseMove (https://editor.graphite.rs/js/123.8b98810b.js:1:8258)
    at Proxy.<anonymous> (https://editor.graphite.rs/js/app.6a8dfb0c.js:1:532)
    at m (https://editor.graphite.rs/js/app.6a8dfb0c.js:1:25571)
    at action (https://editor.graphite.rs/js/app.6a8dfb0c.js:1:23818)
```

**Comment by 0HyperCube** [comment]
This is due to the fact that in order to resize the edge of the transform bounds, we are trying to multiply the line by a matrix with a scale of `new_dimensions_of_bounding_box / old_dimensions_of_bounding_box` (which would here result in infinity as `old_dimensions_of_bounding_box = 0`)

**Comment by otdavies** [comment]
Unassigned myself as it looks like a newer contributor wants to give this a go.
