### ISSUE TITLE
Exporting in `View Mode: Outline` resulted outlines to be exported

### ISSUE THREAD

**Issue by brainwo** [GraphiteEditor/Graphite#788]
**Expected Behaviour**

It should exported the document as seen in `View Mode: Normal` instead. Another suggestion would be to have `View Mode: Outline` export as a separate export option (if necessary).

**Steps to Reproduce**

1. Switch from `View Mode: Normal` to `View Mode: Outline`
1. Export document
1. Saved document is in outline mode

**Comment by Keavon** [comment]
Thanks for finding this. It isn't necessary to provide an option to export in outline mode, that wouldn't be helpful to users.

**Comment by brainwo** [comment]
@Keavon I'll work on this
