### ISSUE TITLE
[Crash Report] When loading auto-saved documents, an image in a non-active tab can't find its layer

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#797]
**Describe the Crash**
When reloading the page, the auto-save system reloads all the saved documents consecutively. If the first tab's document has a layer, it sends a FrontendMessage which will then asynchronously generate a blob URL and eventually call back to the backend with that URL to assign to its layer in that document. But by then, the document loading has moved onto the next document and it has made that one be active. It is then unable to find the Image layer in the first document for some reason.

**Steps To Reproduce**
Describe precisely how the crash occurred, step by step, starting with a new editor window.
1. Open the Graphite Editor at https://editor.graphite.rs
2. Paste an image into the document
3. Make a new document
4. Draw a shape or something
5. Reload the page

**Browser and OS**
Chrome 105, Windows 10 or 11

**Stack Trace**
Copied from the crash dialog in the Graphite Editor:

```
panicked at 'Blob url for invalid layer: LayerNotFound([])', graphene/src/document.rs:757:51

Error
    at https://dev.graphite.rs/js/app.9f6d9d9c.js:9:995
    at Object.n [as handleJsMessage] (https://dev.graphite.rs/js/app.9f6d9d9c.js:1:8158)
    at https://dev.graphite.rs/js/app.9f6d9d9c.js:1:8656
    at https://dev.graphite.rs/js/123.33d206ae.js:1:13830
    at N (https://dev.graphite.rs/js/123.33d206ae.js:1:5550)
    at Cn (https://dev.graphite.rs/js/123.33d206ae.js:1:13796)
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[2323]:0x1c801a
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[912]:0x1741bf
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[699]:0x158434
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[1887]:0x1bb875
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[1764]:0x1b6229
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[1974]:0x1bed08
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[2530]:0x1cbea4
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[2538]:0x1cc07b
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[2057]:0x1c1618
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[53]:0x11a64
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[54]:0x1819c
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[58]:0x2810a
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[131]:0x9d3ac
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[905]:0x173599
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[872]:0x16f5bb
    at https://dev.graphite.rs/cd8ddf81a0c422b7.module.wasm:wasm-function[1979]:0x1bef68
    at Proxy.setImageBlobUrl (https://dev.graphite.rs/js/123.33d206ae.js:1:11040)
    at Proxy.<anonymous> (https://dev.graphite.rs/js/app.9f6d9d9c.js:1:532)
    at https://dev.graphite.rs/js/app.9f6d9d9c.js:1:9069
```

**Comment by 0HyperCube** [comment]
> It is then unable to find the Image layer in the first document for some reason.

This is because messages can only ever be sent to the current active document @Keavon

**Comment by Keavon** [comment]
@0HyperCube it's a little weirder than that, because I have an unpushed branch that depends on the AI Artist branch which fixes that. The result is that the actual document, if you print out the root, is missing the image layer. I'll ping you to take a look when I merge that branch.
