### ISSUE TITLE
Restore length of handle after releasing Shift for mirroring handle lengths with Path tool

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#818]
Right now with the Path tool, if you hold <kbd>Shift</kbd> it will mirror the length of the handle on the opposite side of the handle you're currently dragging. But when you release the key, it leaves it at the current length. To prevent an accidental loss of information, it should snap back to the length right before the key was first held down.

It would also be nice to have the Shift key create the second handle on the opposite side if you are dragging a handle on an anchor with only one handle. Releasing Shift should restore it back to a single-handle anchor.

**Comment by ShouvikGhosh2048** [comment]
I'm working on this issue.
