### ISSUE TITLE
Implement the Path Tool for Bezier curve editing

### ISSUE THREAD

**Issue by edwin0cheng** [GraphiteEditor/Graphite#82]
* Create a system for dealing with points.
* The visualization part eventually involves the Viewport Overlays system (#99), but we can temporarily use the already-implemented system for "working layers" (shapes drawn to the canvas in a preview state before they get committed to the document).
* De-conflicting clicks when multiple points are very close together (using Blender's method of picking the one based on distance from the mouse to the edge connected to that point, so you move your mouse closer to one side or the other of the path edge to prioritize one point or the other)
* Points are extracted from all layers but not occluded by the fill of other layers (that's a complexity of behavior we can address later.)

Goes hand-in-hand with #185, the Pen Tool, which creates the Bezier paths similarly to how the Path Tool edits them.

Complexity: 3
Involves: Editor (Rust), Document (Rust)

**Comment by Keavon** [comment]
Related: https://github.com/GraphiteEditor/Graphite/issues/99

**Comment by Keavon** [comment]
Mainly this requires a system for bezier paths and dealing with points. We might want to wait until our node system can convert basic shape nodes into bezier paths. Or we can do this earlier (destructively) without the full node sytem.

**Comment by Keavon** [comment]
More or less blocked on the transform API (#251).

**Comment by Keavon** [comment]
For the record: this is also being worked on by @emcat. (Please commit the code so we can continue working on it shortly if you don't have time immediately, by the way. Thanks!)
