### ISSUE TITLE
Double clicking an anchor point with the Path tool only shows one handle near start/end point of path

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#821]
On any closed shape, double clicking to sharpen the points, then double clicking again to get the two handles back works except on the two points around the start/end of the path. In that case, it only recovers one handle.

https://user-images.githubusercontent.com/4388688/200951285-5be0071b-1c1e-4dce-8894-0390debc5b70.mp4

**Comment by Keavon** [comment]
Some context in these two commits:

https://github.com/GraphiteEditor/Graphite/commit/d44e7ff925dac79eb372e5f70a77e3b7a95f8a6a
https://github.com/GraphiteEditor/Graphite/commit/74b2737f1f6fdc42a4a255363ef767c9486413cd

**Comment by Torbatti** [comment]
Hi , trying to solve this issue
