### ISSUE TITLE
Tools interrupted in their drag phase break when returning to the tool

### ISSUE THREAD

**Issue by MhmCats** [GraphiteEditor/Graphite#86]
## Description

When drawing with the 'Pen' tool and switching the tool prematurely (before you have clicked enter) and then going back to the Pen tool and moving the mouse cursor around a bit, this happens

![screen-capture](https://user-images.githubusercontent.com/71032999/116244398-cc860900-a75f-11eb-8414-46f63c49c0dd.gif)

## Reproduction steps

1. Start drawing with the pen tool
2. Don't press enter and have the line still following the cursor
3. Click on any other tool and draw with it
4. Click back onto the pen tool and move your mouse around

To be honest I think that it looked nice but probably wasn't intended to happen.

**Comment by 0HyperCube** [comment]
This can also be replicated with other tools, for example if you start drawing a rectangle and then press 'E' without letting go of the mouse button and committing the operation, use another tool and then change back to the rectangle tool then it draws many rectangles
![recording](https://user-images.githubusercontent.com/78500760/116726051-aa4bef80-a9da-11eb-8f90-764c9ed76489.gif)

**Comment by Keavon** [comment]
@pkupper this is related to the other changes you've been making, would you like to assign this bug to yourself?

**Comment by TrueDoctor** [comment]
This is mostly fixed by the new input system, the inconvenience of  having to click twice after a new tool is selected (if you do the drag thing) will be addressed once we properly implement the input preprocessor
