### ISSUE TITLE
The app is blocked

### ISSUE THREAD

**Issue by Adrian8x** [GraphiteEditor/Graphite#88]
Hello,

I tryed to do something in app posted here but is blocked.

https://editor.graphite.design/

**Comment by bjorn3** [comment]
What do you mean with that it is blocked? What do you see?

**Comment by Adrian8x** [comment]
![image](https://user-images.githubusercontent.com/17555902/116542554-69c67600-a8f5-11eb-9583-2c048ac7ac7c.png)

I see this but I can't close tabs, I cand open File, Edit, Document tabs.

**Comment by maroider** [comment]
Many parts of the UI are non-functional since Graphite is in a very early phase of development.

**Comment by Keavon** [comment]
These are not yet implemented.
