### ISSUE TITLE
Hack in a way to clear stuck overlays

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#908]
Switching documents and/or disabling overlays should force clear all overlays, since there's currently no way to fix a stuck overlay. This would mitigate that.

**Comment by 0HyperCube** [comment]
How do I reproduce a stuck overlay?

**Comment by Keavon** [comment]
No idea, it's pretty rare, sorry ¯\_(ツ)_/¯

**Comment by 0HyperCube** [comment]
Do you remember which tool got the overlays stuck?

**Comment by Keavon** [comment]
It happened most recently during the Rust Gamedev Meetup, so we have it on video. The Select tool, it seems. Here's a timestamp (within ~20 seconds, this shows the leadup): https://youtu.be/Ck2R0yqTLcU?t=3721

**Comment by 0HyperCube** [comment]
Thanks - I can reproduce this - this is probably due to the empty folder not having any bounding box. If you have any other instances of this I'll have a look into them.

**Comment by Keavon** [comment]
Amazing, finally a reproduction for this very elusive bug (or at least one instance of it). Have you been able to test if this PR works to forcibly clear the overlay?
