### ISSUE TITLE
Alt+Arrows should nudge to resize the bottom/right edges of layers

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#930]
Currently we can nudge with the arrow keys, which translates the entire layer by 1px or 10px (while holding <kbd>Shift</kbd>). This feature calls for nudging the bottom or right edge, resulting in resizing the layer (pivoting around the top-left corner) instead of translating it, when the user is holding the <kbd>Alt</kbd> modifier in addition to tapping the arrows. Furthermore, adding also the <kbd>Ctrl</kbd> modifier should make it instead scale the top or left sides (pivoting around the bottom-right corner).

Further details (original issue description):

Similar to arrow keys (and the <kbd>Shift</kbd> modifier) to nudge the position of selected layer(s), this feature should "nudge" (by resizing) the right and bottom sides of the selected layer(s). Left and right arrows resize the layer(s) by 1px on the right edge. Up and down arrows resize the layer(s) by 1px on the bottom edge. The <kbd>Shift</kbd> makes it 10px. ~~This should happen in layer space, not viewport space, so regardless of viewport zoom the user should expect to see the dimensions in the Properties panel change by 1px or 10px in W or H. If the layer is rotated, it should scale along the axis of the layer, so the X and Y would change as expected but the W and H would not necessarily change by 1px/10px.~~ The bounding box should be resized, meaning if the layer is rotated, it can become skewed. Assuming it doesn't conflict with any other keys, <kbd>Ctrl</kbd> would be nice as a modifier that changes it to the Left/Top instead of Bottom/Right.

**Comment by 0HyperCube** [comment]
The winding order for rectangles created with the rectangle tool is arbitrary and doesn't change, and with the path tool it is based upon the order the points are added by the user, so I doubt this is the issue.

**Comment by Keavon** [comment]
We probably need to enforce a standard winding order for all shapes, including those made with the Pen tool regardless of whether the user drew the shape in the CW or CCW direction. But it's worth doing some research to see if that's how it should be handled.

**Comment by Sahra-Zhou** [comment]
#990
