### ISSUE TITLE
New feature: support outline stroke for font object

### ISSUE THREAD

**Issue by nine-fox** [GraphiteEditor/Graphite#938]
Hi there,

I just found Graphite is really a great tool! With lots of expectations, I would like to submit a feature:

Support to outline stroke for font. 

Since this is a quite basic operations for vector font design. Thanks!

nine-fox

**Comment by Keavon** [comment]
Hi! This is already supported. You just have to set a nonzero stroke weight and a color of your choice.

![image](https://user-images.githubusercontent.com/4388688/210237962-a5dd5f2d-458a-4721-9218-7d4ce74757a8.png)

If you are talking about something else, could you please clarify? I can reopen the issue if that's the case.

**Comment by nine-fox** [comment]
> Hi! This is already supported. You just have to set a nonzero stroke weight and a color of your choice.
> 
> ![image](https://user-images.githubusercontent.com/4388688/210237962-a5dd5f2d-458a-4721-9218-7d4ce74757a8.png)
> 
> If you are talking about something else, could you please clarify? I can reopen the issue if that's the case.

Hi Keavon, thanks very much for your reply on this topic. Sorry I should clarify my case.

I did saw the stroke settings for the text object. However, I *cannot* edit this stroke path. For example, I created a Arial with "hello world" and then edit "h" to use a customized shape - for example, enlarge it using bezier point.

That is, I need to convert a Text object to a normal shape object.

Or maybe I missed something and Graphite already support it. Please let me know if I am wrong. Thanks!

**Comment by nine-fox** [comment]
The "Outline Stroke" is an action from Sigma tool. Select a text and right click mouse. You can see "Outline Stroke" there - which I used a lot in Sigma, by the way.

**Comment by Keavon** [comment]
Thanks for clarifying. We did have this feature in the past, but it was removed when we made some big code changes and we haven't added it back yet. I just filed an issue for it here: #940. Feel free to subscribe to that issue if you'd like updates to its status.

**Comment by nine-fox** [comment]
> Thanks for clarifying. We did have this feature in the past, but it was removed when we made some big code changes and we haven't added it back yet. I just filed an issue for it here: #940. Feel free to subscribe to that issue if you'd like updates to its status.

OK. thanks for your investigation and looking forward to this feature be online.
