### ISSUE TITLE
Improve Artboard tool selection behavior

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#944]
First, we want to always draw border overlays around all artboards to clarify what's clickable. Then, we need to default to one artboard always being selected (for discoverability, to avoid confusion about how you resize an artboard without any obvious handles shown). The user shouldn't be able to deselect all artboards to have 0 selected. For now, the artboard highest in the layer stack can be the default, and the tool saves which artboard was most recently selected (even if the tool has been switched away from, and then back to).

**Comment by mariusa** [comment]
Would you please briefly explain whats an Artboard and possible uses? I searched through other issues and tried it out. Thanks :)

**Comment by 0HyperCube** [comment]
Artboards our the equivalent to inkscape's pages - https://media.inkscape.org/media/doc/release_notes/1.2/Inkscape_1.2.html#Page_tool @mariusa.

**Comment by Keavon** [comment]
We might even want to call it a page someday as we move towards supporting digital publishing workflows with pages and spreads.

**Comment by Keavon** [comment]
Looking at this issue again, I'm thinking it's no longer necessary. Now that we have artboard names in the top left, it's clearer what is an artboard, negating the need for an outline around each artboard. I'm also not sure that we want to default to one being selected anymore, because that would mean the actual layer selection state gets changed just by moving to another tool, which is probably not desirable.
