### ISSUE TITLE
UX: After Import, switch to Select tool

### ISSUE THREAD

**Issue by mariusa** [GraphiteEditor/Graphite#957]
Steps:
1. Have a drawing tool selected, eg line
2. Import a graphic

My next reaction after importing was to move & resize it, but instead I drew a line :)

Proposal: After Import, switch to Select tool, so users can start to manipulate newly imported object.

**Comment by Keavon** [comment]
Good suggestion, I agree. This should happen for File > Import as well as dragging an image into the viewport.

**Comment by auto-kad** [comment]
I'd like to start working on this issue
