### ISSUE TITLE
UX: resize object with drag should respect 'Preserve Aspect Ratio' checkbox

### ISSUE THREAD

**Issue by mariusa** [GraphiteEditor/Graphite#958]
Hi, following up on https://github.com/GraphiteEditor/Graphite/pull/923

I did a usability test with a non-tech person, asking her to insert an image and resizing it. She couldn't manage to keep aspect ratio. She did see the checkbox, but apparently "it doesn't work".

I'd like to argue that it's more intuitive to have the visual (mouse/drag) resize respect the checkbox, and have Shift key to temporarily reverse the checkbox setting. Also, on a tablet there's no Shift key to press while resizing with fingers.

Ideally, pressing Shift would also change the visual checkbox state (only while it's pressed).

**Comment by Keavon** [comment]
I agree that inexperienced users will usually fail to preserve aspect ratio when they intend to by holding <kbd>Shift</kbd>. I'm not sure how intuitive it will be to link that checkbox with the behavior of the Select tool though, but that's worth revisiting once tools are coupled with nodes and the Transform node replaces the current Transform section in the layer properties. Perhaps a good way to improve the situation is defaulting to preserving the aspect ratio except when holding Shift to opt out.

**Comment by mariusa** [comment]
> Perhaps a good way to improve the situation is defaulting to preserving the aspect ratio except when holding Shift to opt out.

That would be great!

**Comment by Keavon** [comment]
Closing this since I don't think the UX would be best in this particular way, but work can definitely be done over time to improve the clarity of the root problem.
