### ISSUE TITLE
Reaching end of undo/redo history spams console

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#969]
Calling redo multiple times after all redo history has been exhausted spams the JS console with "A rollback was initiated but no transaction was in progress". This isn't desirable. Is it indicative of a bug, or does that warning message just need to be removed?

**Comment by 0HyperCube** [comment]
It doesn't spam the console, it simply displays a single warning for each time Ctrl+Z is pressed, which is useful if you are debugging something where you expect a history state to have been created.

**Comment by Keavon** [comment]
That's what I meant by spam, yeah, once per button press. It should probably be turned into a trace not a warn? The idea is that, ideally without any bugs in our software, the user should be able to open the console and never see anything show up.

**Comment by Keavon** [comment]
This was fixed a while back.
