### ISSUE TITLE
Undo/redo last point extended using the Pen tool

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#971]
Each point drawn with the pen tool while it performs its role of extending a vector shape's path should be integrated into the history so undo/redo can step through line extension steps.

**Comment by auto-kad** [comment]
I'll work on this

**Comment by Keavon** [comment]
@zhiyuang please leave a comment in this issue.

**Comment by zhiyuang** [comment]
Assign to me 😃
