### ISSUE TITLE
Make draggable widgets set only one undo/redo state upon committing a value

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#972]
Draggable number input sliders, color pickers, typeable text fields, and any other widgets we may have now or in the future should be able to send two types of values to the backend. An "update" and a "commit". The former should preview the change like it does now, while the latter should set a history state. Reference the text input widgets for something conceptually related (but not fully implemented end-to-end like this issue describes) regarding an update vs. a commit of a value change. That should use the same system.

Currently we set a history point for every change which wipes out history with tons of small changes caused by single-pixel drag movements in the widgets.

**Comment by Keavon** [comment]
@zhiyuang please leave a comment in this issue.

**Comment by zhiyuang** [comment]
The root cause is that right now always trigger `Document.StartTransaction` to save a history step. I have raised a PR to split update and commit. And then we only trigger `Document.StartTransaction` on commit action, not update action.

**Comment by Keavon** [comment]
Thanks @zhiyuang. And for future reference, no need to give an elaborate comment, I just need any comment at all so GitHub lets me assign you the issue.
