### ISSUE TITLE
Approachable mini starter tasks for new contributors

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#989]
All of these are approachable as a first issue for beginners. Those specifically marked as "easy" should be simple enough for less experienced Rust programmers, but they should all be doable with some patience. Before beginning any of these, please ask for clarification about what the issue precisely means and make sure you can reproduce the issue firsthand to understand what's needed. Ask @Keavon for a video clip in Discord if clarification is needed.

This issue is meant to list all the small tasks that didn't warrant their own issue. Please check the [Good First Issue](https://github.com/GraphiteEditor/Graphite/labels/Good%20First%20Issue) tag for a list of other issues that suit this. The majority of those should be reasonably approachable for new Rust programmers, although some of those might assume a bit more Rust experience. Please ask if unsure.

*All gone for now, this issue is closed for the time being*

**Comment by ajjahn** [comment]
> Easy: Enter on a single selected text layer should enter text editing mode (selecting everything, just like double clicking). [(As posted in Discord)](https://discord.com/channels/731730685944922173/881073965047636018/939765200809263134)

I think this was completed in #1000.

**Comment by Keavon** [comment]
Indeed, thanks for the note.
