### ISSUE TITLE
Make the Pen tool not show the in-progress segment until committed

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#999]
### Current behavior:
The extending segment is updated while the mouse moves to show the shape as it will appear. This is undesirable because it can get in the way of viewing something you're tracing over.

https://user-images.githubusercontent.com/4388688/215305080-fff17869-3366-4cf0-8a0e-5a044a9a740e.mp4

### Desired behavior:
The extending segment is updated only after releasing the mouse cursor to commit the new segment. Only the thin blue overlay should show the extension preview.

https://user-images.githubusercontent.com/4388688/215305489-ca9cbc12-1b1a-4503-bef6-8046bbf62ff9.mp4

It should apply to the Pen tool only.

**Comment by 0HyperCube** [comment]
I'm not sure how you envision this working with the spline tool as placing a new point effects all previous segments.

**Comment by Keavon** [comment]
Hmmm, good point. Maybe let's de-scope this for the spline tool then.
